In [1]:
import os

# These must be set before importing any Hugging Face or sae_lens modules
os.environ["TRANSFORMERS_CACHE"] = "/shared/3/projects/bangzhao/models/transformers"
os.environ["HF_DATASETS_CACHE"] = "/shared/3/projects/bangzhao/models/datasets"
os.environ["HF_TOKENIZERS_CACHE"] = "/shared/3/projects/bangzhao/models/tokenizers"
os.environ["HF_HOME"] = "/shared/3/projects/bangzhao/models"  # fallback root

from huggingface_hub import login
login(token="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")

In [2]:
try:
    import google.colab  # type: ignore
    from google.colab import output

    COLAB = True
    %pip install sae-lens transformer-lens sae-dashboard
except:
    COLAB = False
    from IPython import get_ipython  # type: ignore

    ipython = get_ipython()
    assert ipython is not None
    ipython.run_line_magic("load_ext", "autoreload")
    ipython.run_line_magic("autoreload", "2")

# Standard imports
import os
import torch
from tqdm import tqdm
import plotly.express as px
import pandas as pd

# Imports for displaying vis in Colab / notebook

torch.set_grad_enabled(False)

# For the most part I'll try to import functions and classes near where they are used
# to make it clear where they come from.

if torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cuda:1" if torch.cuda.is_available() else "cpu"

print(f"Device: {device}")

Device: cuda:1

In [3]:
from sae_lens.toolkit.pretrained_saes_directory import get_pretrained_saes_directory

# TODO: Make this nicer.
df = pd.DataFrame.from_records(
    {k: v.__dict__ for k, v in get_pretrained_saes_directory().items()}
).T
df.drop(
    columns=[
        "expected_var_explained",
        "expected_l0",
        "config_overrides",
        "conversion_func",
    ],
    inplace=True,
)

/opt/anaconda/lib/python3.12/site-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
2025-08-08 18:22:23.605871: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-08-08 18:22:23.620642: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1754677343.635426 3860030 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1754677343.639841 3860030 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1754677343.652438 3860030 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1754677343.652452 3860030 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1754677343.652453 3860030 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1754677343.652454 3860030 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-08-08 18:22:23.657253: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [4]:
filtered_df = df[df['model'].str.contains('gemma-2-9b-it', na=False)]
filtered_df

,release,repo_id,model,saes_map,neuronpedia_id
gemma-scope-9b-it-res-canonical,gemma-scope-9b-it-res-canonical,google/gemma-scope-9b-it-res,gemma-2-9b-it,{'layer_9/width_16k/canonical': 'layer_9/width...,{'layer_9/width_16k/canonical': 'gemma-2-9b-it...

In [5]:
filtered_df[filtered_df["release"]=="gemma-scope-9b-it-res-canonical"].saes_map.iloc[0]

{'layer_9/width_16k/canonical': 'layer_9/width_16k/average_l0_88',
 'layer_20/width_16k/canonical': 'layer_20/width_16k/average_l0_91',
 'layer_31/width_16k/canonical': 'layer_31/width_16k/average_l0_76',
 'layer_9/width_131k/canonical': 'layer_9/width_131k/average_l0_121',
 'layer_20/width_131k/canonical': 'layer_20/width_131k/average_l0_81',
 'layer_31/width_131k/canonical': 'layer_31/width_131k/average_l0_109'}

# Loading a pretrained Sparse Autoencoder

As a first step, we will actually load an SAE! But before we do so, it can be useful to see which are available. The following snippet shows the currently available SAE releases in SAELens, and will remain up-to-date as we continue to add more SAEs.

In [6]:
# from transformer_lens import HookedTransformer
from sae_lens import SAE, HookedSAETransformer

# model = HookedSAETransformer.from_pretrained("gemma-2-9b", device=device)
model = HookedSAETransformer.from_pretrained("gemma-2-9b-it", device=device)

# the cfg dict is returned alongside the SAE since it may contain useful information for analysing the SAE (eg: instantiating an activation store)
# Note that this is not the same as the SAEs config dict, rather it is whatever was in the HF repo, from which we can extract the SAE config dict
# We also return the feature sparsities which are stored in HF for convenience.
sae, cfg_dict, sparsity = SAE.from_pretrained(
    release="gemma-scope-9b-it-res-canonical",  # <- Release name
    sae_id="layer_20/width_16k/canonical",  # <- SAE id (not always a hook point!)
    device=device,
)

WARNING:root:You tried to specify center_unembed=True for a model using logit softcap, but this can't be done! Softcapping is not invariant upon adding a constant Setting center_unembed=False instead.

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

WARNING:root:You are not using LayerNorm, so the writing weights can't be centered! Skipping

Loaded pretrained model gemma-2-9b-it into HookedTransformer

In [7]:
print(sae.cfg.__dict__)

{'architecture': 'jumprelu', 'd_in': 3584, 'd_sae': 16384, 'activation_fn_str': 'relu', 'apply_b_dec_to_input': False, 'finetuning_scaling_factor': False, 'context_size': 1024, 'model_name': 'gemma-2-9b-it', 'hook_name': 'blocks.20.hook_resid_post', 'hook_layer': 20, 'hook_head_index': None, 'prepend_bos': True, 'dataset_path': 'monology/pile-uncopyrighted', 'dataset_trust_remote_code': True, 'normalize_activations': None, 'dtype': 'float32', 'device': 'cuda:1', 'sae_lens_training_version': None, 'activation_fn_kwargs': {}, 'neuronpedia_id': 'gemma-2-9b-it/20-gemmascope-res-16k', 'model_from_pretrained_kwargs': {}, 'seqpos_slice': (None,)}

## Load Dataset

In [8]:
isear = pd.read_csv("/shared/3/projects/bangzhao/interpretability/gemma2_9b_it_isear.csv")
isear.rename(columns={'Field1': 'label'}, inplace=True)
isear['output'] = isear['output'].str.lower().str.strip()

In [9]:
isear.head(2)

      ID                                                SIT  label output
0  11001  During the period of falling in love, each tim...    joy    joy
1  11001  When I was driving home after  several days of...  anger  anger

In [10]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(isear, test_size=0.1, random_state=42)

In [11]:
len(train_df)

2730

In [12]:
prompt = """Choose the most appropriate emotion from the following list: joy, sadness, anger, disgust, fear, guilt, and shame. Respond with only the emotion, without any explanation.
Experience: {text} 
Answer: {emotion}"""

In [13]:
train_correct_prompts = [
    prompt.format(text=row['SIT'], emotion=row['label'])
    for _, row in train_df.iterrows()
]

train_error_prompts = [
    prompt.format(text=row['SIT'], emotion=row['output'])
    for _, row in train_df.iterrows()
]

## SVD

In [14]:
from tqdm import tqdm
import numpy as np
import torch

matrix_correct = []
torch.cuda.empty_cache()

for i in tqdm(range(len(train_df)), desc="Processing correct prompts"):
    prompt = train_correct_prompts[i].strip()
    
    # Run model and get cache
    _, cache = model.run_with_cache_with_saes(prompt, saes=[sae])
    
    # Extract the final-layer SAE feature from the last token
    features = cache["blocks.20.hook_resid_post.hook_sae_acts_post"][0, -1, :].detach().cpu()
    matrix_correct.append(features.numpy())
    
    # Explicitly delete cache and free memory
    del cache
    torch.cuda.empty_cache()

Processing correct prompts: 100%|███████████| 2730/2730 [10:20<00:00,  4.40it/s]

In [15]:
matrix_correct = np.stack(matrix_correct)

In [16]:
matrix_error = []
torch.cuda.empty_cache()

for i in tqdm(range(len(train_df)), desc="Processing correct prompts"):
    prompt = train_error_prompts[i].strip()
    
    # Run model and get cache
    _, cache = model.run_with_cache_with_saes(prompt, saes=[sae])
    
    # Extract the final-layer SAE feature from the last token
    features = cache["blocks.20.hook_resid_post.hook_sae_acts_post"][0, -1, :].detach().cpu()
    matrix_error.append(features.numpy())
    
    # Explicitly delete cache and free memory
    del cache
    torch.cuda.empty_cache()

matrix_error = np.stack(matrix_error)

Processing correct prompts: 100%|█████████| 2730/2730 [10:26<00:00,  4.36it/s]

In [17]:
matrix_error.shape

(2730, 16384)

In [18]:
matrix_correct_centered = matrix_correct - matrix_correct.mean(axis=0)
matrix_error_centered = matrix_error - matrix_error.mean(axis=0)

U_c, S_c, Vt_c = np.linalg.svd(matrix_correct_centered, full_matrices=False)
U_e, S_e, Vt_e = np.linalg.svd(matrix_error_centered, full_matrices=False)

d = 5  # number of components
V_c_top = Vt_c[:d, :]  # top-5 feature directions from correct matrix
V_e_top = Vt_e[:d, :]  # top-5 feature directions from error matrix

V_c_top.shape

# Top-1 principal directions
v_c = Vt_c[0]  # shape: (16384,)
v_e = Vt_e[0]

# Steering vector
delta = v_c - v_e  # shape: (16384,)

In [19]:
# Center the matrices
matrix_correct_centered = matrix_correct - matrix_correct.mean(axis=0)
matrix_error_centered = matrix_error - matrix_error.mean(axis=0)

# Perform SVD
U_c, S_c, Vt_c = np.linalg.svd(matrix_correct_centered, full_matrices=False)
U_e, S_e, Vt_e = np.linalg.svd(matrix_error_centered, full_matrices=False)

# Number of components
d = 10

# Top-d feature directions
V_c_top = Vt_c[:d, :]  # shape: (d, features)
V_e_top = Vt_e[:d, :]  # shape: (d, features)

# Singular values as weights
weights = S_c[:d]  # Option A: use raw singular values

# Weighted difference of components
delta_components = V_c_top - V_e_top  # shape: (d, features)
steering_vector = np.average(delta_components, axis=0, weights=weights)

# Normalize the steering vector
steering_vector /= np.linalg.norm(steering_vector)

# Now `steering_vector` is your weighted delta direction

In [20]:
steering_vector.shape

(16384,)

In [21]:
steering_vector

array([ 7.1785473e-17, -1.5765545e-16,  7.4697193e-05, ...,
        2.8025289e-03,  2.4124074e-03, -1.6674923e-03], dtype=float32)

In [22]:
topk_indices = np.argsort(np.abs(steering_vector))[-20:][::-1]

# Get their corresponding magnitudes
topk_magnitudes = np.abs(steering_vector[topk_indices])
topk_features = list(zip(topk_indices, topk_magnitudes))

for idx, mag in topk_features:
    print(f"Feature {idx} has magnitude {mag:.4f}")

Feature 10737 has magnitude 0.2764
Feature 3344 has magnitude 0.2294
Feature 7162 has magnitude 0.2245
Feature 3268 has magnitude 0.1873
Feature 9374 has magnitude 0.1695
Feature 1295 has magnitude 0.1579
Feature 1557 has magnitude 0.1554
Feature 6670 has magnitude 0.1451
Feature 14962 has magnitude 0.1366
Feature 3373 has magnitude 0.1340
Feature 3740 has magnitude 0.1280
Feature 12407 has magnitude 0.1248
Feature 3827 has magnitude 0.1243
Feature 1284 has magnitude 0.1126
Feature 1393 has magnitude 0.1125
Feature 10079 has magnitude 0.1090
Feature 12257 has magnitude 0.1053
Feature 1254 has magnitude 0.1032
Feature 3994 has magnitude 0.0999
Feature 8627 has magnitude 0.0999

In [23]:
from IPython.display import IFrame


html_template = "https://neuronpedia.org/{}/{}/{}?embed=true&embedexplanation=true&embedplots=true&embedtest=true&height=300"

def get_dashboard_html(sae_release="gemma-2-9b-it", sae_id="20-gemmascope-res-16k", feature_idx=0):
    return html_template.format(sae_release, sae_id, feature_idx)

html = get_dashboard_html(
    sae_release="gemma-2-9b-it", sae_id="20-gemmascope-res-16k", feature_idx=7162
)
IFrame(html, width=1200, height=600)

## optimization

In [24]:
from datasets import load_dataset

hf_dataset = load_dataset("allenai/c4", "en", split="train", streaming=True)

Resolving data files:   0%|          | 0/1024 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/1024 [00:00<?, ?it/s]

In [25]:
# instantiate an object to hold activations from a dataset
from sae_lens import ActivationsStore

# a convenient way to instantiate an activation store is to use the from_sae method
activation_store = ActivationsStore.from_sae(
    model=model,
    sae=sae,
    streaming=True,
    dataset=hf_dataset,
    # fairly conservative parameters here so can use same for larger
    # models without running out of memory.
    store_batch_size_prompts=8,
    train_batch_size_tokens=4096,
    n_batches_in_buffer=32,
    device=device,
)

/home/bangzhao/.local/lib/python3.12/site-packages/sae_lens/training/activations_store.py:301: UserWarning: Dataset is not tokenized. Pre-tokenizing will improve performance and allows for more control over special tokens. See https://jbloomaus.github.io/SAELens/training_saes/#pretokenizing-datasets for more info.
  warnings.warn(

In [26]:
from tqdm import tqdm
from functools import partial


def steering(activations, hook, steering_strength=1.0, steering_vector=None):
    return activations + steering_strength * steering_vector


def generate_with_steering(
    model,
    sae,
    prompt,
    svd_direction,
    steering_strength=1.0,
    max_new_tokens=16,
):
    input_ids = model.to_tokens(prompt, prepend_bos=sae.cfg.prepend_bos)
    print(svd_direction.shape)
    print(sae.W_dec.shape)

    svd_direction = torch.tensor(svd_direction, device=sae.W_dec.device, dtype=sae.W_dec.dtype)
    steering_vector = (svd_direction @ sae.W_dec).to(model.cfg.device)
    # steering_vector = sae.W_dec[steering_feature].to(model.cfg.device)

    steering_hook = partial(
        steering,
        steering_vector=steering_vector,
        steering_strength=steering_strength
    )

    # standard transformerlens syntax for a hook context for generation
    with model.hooks(fwd_hooks=[(sae.cfg.hook_name, steering_hook)]):
        output = model.generate(
            input_ids,
            max_new_tokens=max_new_tokens,
            temperature=0.001,
            stop_at_eos=False if device == "mps" else True,
            prepend_bos=sae.cfg.prepend_bos,
        )

    return model.tokenizer.decode(output[0])
    

def find_max_activations_all_features(model, sae, activation_store, num_batches=100):
    """
    Find the maximum activation for all features in the SAE.
    Returns a tensor of shape (num_features,)
    """
    num_features = sae.cfg.d_sae  # usually 16,384
    max_activations = torch.zeros(num_features, device='cuda:1')  # or use .cpu() if needed

    pbar = tqdm(range(num_batches))
    for _ in pbar:
        tokens = activation_store.get_batch_tokens()

        _, cache = model.run_with_cache(
            tokens,
            stop_at_layer=sae.cfg.hook_layer + 1,
            names_filter=[sae.cfg.hook_name],
        )
        sae_in = cache[sae.cfg.hook_name]
        feature_acts = sae.encode(sae_in).squeeze()  # shape: [batch, seq_len, d_sae]
        feature_acts = feature_acts.flatten(0, 1)     # shape: [batch*seq_len, d_sae]

        # Update max activations element-wise
        max_activations = torch.max(max_activations, feature_acts.max(dim=0).values)

        pbar.set_description(f"Current max: {max_activations.max().item():.4f}")

    return max_activations.cpu()

In [27]:
max_act = find_max_activations_all_features(model, sae, activation_store)

Current max: 3130.6812: 100%|███████████████| 100/100 [06:31<00:00,  3.92s/it]

In [28]:
steering_vector *= max_act.cpu().numpy()

In [29]:
import pandas as pd
import re
from tqdm import tqdm

# Candidate steering strengths
strength_values = [-0.5, -0.2, -0.1, 0, 1]

# Initialize master list
all_rows = []

for strength in tqdm(strength_values, desc="Steering Strength"):
    rows_for_strength = []  # Temporary storage for this strength value
    for index in tqdm(range(len(train_error_prompts[:300])), desc=f"Strength {strength}", leave=False):
        prompt = train_error_prompts[index].split('\nAnswer:')[0] + "\nAnswer: "
        label = train_error_prompts[index].split('\nAnswer:')[1].strip()

        steered_text = generate_with_steering(model, sae, prompt, svd_direction=steering_vector, steering_strength=strength)
        raw_pred = steered_text.split('\nAnswer:')[1]
        prediction = re.sub(r'<.*?>', '', raw_pred).strip()

        rows_for_strength.append({
            'index': index,
            'steering_strength': strength,
            'label': label,
            'prediction': prediction
        })

    # Save intermediate result for this strength
    df_strength = pd.DataFrame(rows_for_strength)
    df_strength.to_csv(f"/shared/3/projects/bangzhao/interpretability/all-emotions-test/steered_predictions_strength_{strength}.csv", index=False)

    # Append to master list
    all_rows.extend(rows_for_strength)

# Save full result
# df_results = pd.DataFrame(all_rows)
# df_results.to_csv("/shared/3/projects/bangzhao/interpretability/all-emotions-test/steered_predictions_all.csv", index=False)

Steering Strength:   0%|                                | 0/5 [00:00<?, ?it/s]
Strength -0.5:   0%|                                  | 0/300 [00:00<?, ?it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   0%|                          | 1/300 [00:00<03:03,  1.63it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   1%|▏                         | 2/300 [00:01<02:57,  1.68it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   1%|▎                         | 3/300 [00:01<02:53,  1.71it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   1%|▎                         | 4/300 [00:02<02:52,  1.71it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   2%|▍                         | 5/300 [00:02<02:42,  1.81it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   2%|▌                         | 6/300 [00:03<02:37,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   2%|▌                         | 7/300 [00:03<02:17,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   3%|▋                         | 8/300 [00:04<02:27,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   3%|▊                         | 9/300 [00:04<02:41,  1.80it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   3%|▊                        | 10/300 [00:05<02:21,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   4%|▉                        | 11/300 [00:05<02:07,  2.27it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   4%|█                        | 12/300 [00:06<02:11,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   4%|█                        | 13/300 [00:06<02:14,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   5%|█▏                       | 14/300 [00:07<02:16,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   5%|█▎                       | 15/300 [00:07<02:24,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   5%|█▎                       | 16/300 [00:08<02:23,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   6%|█▍                       | 17/300 [00:08<02:21,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   6%|█▌                       | 18/300 [00:09<02:21,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   6%|█▌                       | 19/300 [00:09<02:20,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   7%|█▋                       | 20/300 [00:10<02:26,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   7%|█▊                       | 21/300 [00:10<02:30,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   7%|█▊                       | 22/300 [00:11<02:33,  1.82it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   8%|█▉                       | 23/300 [00:11<02:34,  1.79it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   8%|██                       | 24/300 [00:12<02:35,  1.77it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   8%|██                       | 25/300 [00:13<02:29,  1.84it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   9%|██▏                      | 26/300 [00:13<02:38,  1.73it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   9%|██▎                      | 27/300 [00:14<02:30,  1.81it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:   9%|██▎                      | 28/300 [00:14<02:32,  1.78it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  10%|██▍                      | 29/300 [00:15<02:39,  1.70it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  10%|██▌                      | 30/300 [00:15<02:31,  1.78it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  10%|██▌                      | 31/300 [00:16<02:12,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  11%|██▋                      | 32/300 [00:16<02:12,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  11%|██▊                      | 33/300 [00:17<02:11,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  11%|██▊                      | 34/300 [00:17<02:12,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  12%|██▉                      | 35/300 [00:18<02:18,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  12%|███                      | 36/300 [00:18<02:15,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  12%|███                      | 37/300 [00:19<02:13,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  13%|███▏                     | 38/300 [00:19<02:13,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  13%|███▎                     | 39/300 [00:20<02:11,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  13%|███▎                     | 40/300 [00:20<02:10,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  14%|███▍                     | 41/300 [00:21<02:09,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  14%|███▌                     | 42/300 [00:21<02:21,  1.83it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  14%|███▌                     | 43/300 [00:22<02:16,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  15%|███▋                     | 44/300 [00:23<02:32,  1.67it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  15%|███▊                     | 45/300 [00:23<02:24,  1.77it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  15%|███▊                     | 46/300 [00:24<02:18,  1.84it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  16%|███▉                     | 47/300 [00:24<02:13,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  16%|████                     | 48/300 [00:25<02:10,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  16%|████                     | 49/300 [00:25<02:09,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  17%|████▏                    | 50/300 [00:26<02:08,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  17%|████▎                    | 51/300 [00:26<02:07,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  17%|████▎                    | 52/300 [00:27<02:05,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  18%|████▍                    | 53/300 [00:27<02:04,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  18%|████▌                    | 54/300 [00:28<02:09,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  18%|████▌                    | 55/300 [00:28<02:06,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  19%|████▋                    | 56/300 [00:29<02:04,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  19%|████▊                    | 57/300 [00:29<02:03,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  19%|████▊                    | 58/300 [00:30<02:08,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  20%|████▉                    | 59/300 [00:30<02:06,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  20%|█████                    | 60/300 [00:31<02:03,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  20%|█████                    | 61/300 [00:31<02:07,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  21%|█████▏                   | 62/300 [00:32<02:04,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  21%|█████▎                   | 63/300 [00:32<01:59,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  21%|█████▎                   | 64/300 [00:33<01:58,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  22%|█████▍                   | 65/300 [00:33<01:57,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  22%|█████▌                   | 66/300 [00:34<01:56,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  22%|█████▌                   | 67/300 [00:34<01:55,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  23%|█████▋                   | 68/300 [00:35<01:55,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  23%|█████▊                   | 69/300 [00:35<02:00,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  23%|█████▊                   | 70/300 [00:36<01:58,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  24%|█████▉                   | 71/300 [00:36<01:56,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  24%|██████                   | 72/300 [00:37<02:06,  1.80it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  24%|██████                   | 73/300 [00:38<02:12,  1.71it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  25%|██████▏                  | 74/300 [00:38<02:12,  1.71it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  25%|██████▎                  | 75/300 [00:39<02:05,  1.79it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  25%|██████▎                  | 76/300 [00:39<02:00,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  26%|██████▍                  | 77/300 [00:40<01:58,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  26%|██████▌                  | 78/300 [00:40<02:00,  1.84it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  26%|██████▌                  | 79/300 [00:41<01:45,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  27%|██████▋                  | 80/300 [00:41<01:46,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  27%|██████▊                  | 81/300 [00:42<01:47,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  27%|██████▊                  | 82/300 [00:42<01:47,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  28%|██████▉                  | 83/300 [00:43<01:47,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  28%|███████                  | 84/300 [00:43<01:46,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  28%|███████                  | 85/300 [00:44<01:46,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  29%|███████▏                 | 86/300 [00:44<01:45,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  29%|███████▏                 | 87/300 [00:45<01:50,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  29%|███████▎                 | 88/300 [00:45<01:48,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  30%|███████▍                 | 89/300 [00:46<01:52,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  30%|███████▌                 | 90/300 [00:46<01:49,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  30%|███████▌                 | 91/300 [00:47<01:47,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  31%|███████▋                 | 92/300 [00:47<01:45,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  31%|███████▊                 | 93/300 [00:48<01:44,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  31%|███████▊                 | 94/300 [00:48<01:43,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  32%|███████▉                 | 95/300 [00:49<01:32,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  32%|████████                 | 96/300 [00:49<01:24,  2.42it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  32%|████████                 | 97/300 [00:50<01:29,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  33%|████████▏                | 98/300 [00:50<01:32,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  33%|████████▎                | 99/300 [00:51<01:34,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  33%|████████                | 100/300 [00:51<01:35,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  34%|████████                | 101/300 [00:51<01:26,  2.30it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  34%|████████▏               | 102/300 [00:52<01:29,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  34%|████████▏               | 103/300 [00:53<01:41,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  35%|████████▎               | 104/300 [00:53<01:44,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  35%|████████▍               | 105/300 [00:54<01:51,  1.75it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  35%|████████▍               | 106/300 [00:54<01:36,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  36%|████████▌               | 107/300 [00:55<01:36,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  36%|████████▋               | 108/300 [00:55<01:40,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  36%|████████▋               | 109/300 [00:56<01:38,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  37%|████████▊               | 110/300 [00:56<01:27,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  37%|████████▉               | 111/300 [00:57<01:33,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  37%|████████▉               | 112/300 [00:57<01:33,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  38%|█████████               | 113/300 [00:58<01:32,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  38%|█████████               | 114/300 [00:58<01:31,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  38%|█████████▏              | 115/300 [00:59<01:31,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  39%|█████████▎              | 116/300 [00:59<01:35,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  39%|█████████▎              | 117/300 [01:00<01:33,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  39%|█████████▍              | 118/300 [01:00<01:32,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  40%|█████████▌              | 119/300 [01:01<01:31,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  40%|█████████▌              | 120/300 [01:01<01:30,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  40%|█████████▋              | 121/300 [01:02<01:29,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  41%|█████████▊              | 122/300 [01:02<01:28,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  41%|█████████▊              | 123/300 [01:03<01:27,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  41%|█████████▉              | 124/300 [01:03<01:27,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  42%|██████████              | 125/300 [01:04<01:26,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  42%|██████████              | 126/300 [01:04<01:30,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  42%|██████████▏             | 127/300 [01:05<01:28,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  43%|██████████▏             | 128/300 [01:05<01:27,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  43%|██████████▎             | 129/300 [01:06<01:30,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  43%|██████████▍             | 130/300 [01:06<01:27,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  44%|██████████▍             | 131/300 [01:07<01:26,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  44%|██████████▌             | 132/300 [01:07<01:24,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  44%|██████████▋             | 133/300 [01:08<01:24,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  45%|██████████▋             | 134/300 [01:08<01:27,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  45%|██████████▊             | 135/300 [01:09<01:29,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  45%|██████████▉             | 136/300 [01:09<01:26,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  46%|██████████▉             | 137/300 [01:10<01:24,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  46%|███████████             | 138/300 [01:10<01:27,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  46%|███████████             | 139/300 [01:11<01:28,  1.82it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  47%|███████████▏            | 140/300 [01:12<01:27,  1.83it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  47%|███████████▎            | 141/300 [01:12<01:28,  1.80it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  47%|███████████▎            | 142/300 [01:13<01:25,  1.84it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  48%|███████████▍            | 143/300 [01:13<01:15,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  48%|███████████▌            | 144/300 [01:14<01:23,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  48%|███████████▌            | 145/300 [01:14<01:21,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  49%|███████████▋            | 146/300 [01:15<01:22,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  49%|███████████▊            | 147/300 [01:15<01:20,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  49%|███████████▊            | 148/300 [01:16<01:22,  1.84it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  50%|███████████▉            | 149/300 [01:16<01:19,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  50%|████████████            | 150/300 [01:17<01:21,  1.84it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  50%|████████████            | 151/300 [01:17<01:18,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  51%|████████████▏           | 152/300 [01:18<01:17,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  51%|████████████▏           | 153/300 [01:18<01:13,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  51%|████████████▎           | 154/300 [01:19<01:13,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  52%|████████████▍           | 155/300 [01:19<01:15,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  52%|████████████▍           | 156/300 [01:20<01:14,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  52%|████████████▌           | 157/300 [01:20<01:12,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  53%|████████████▋           | 158/300 [01:21<01:11,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  53%|████████████▋           | 159/300 [01:21<01:10,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  53%|████████████▊           | 160/300 [01:22<01:10,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  54%|████████████▉           | 161/300 [01:22<01:09,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  54%|████████████▉           | 162/300 [01:23<01:12,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  54%|█████████████           | 163/300 [01:23<01:11,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  55%|█████████████           | 164/300 [01:24<01:09,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  55%|█████████████▏          | 165/300 [01:25<01:11,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  55%|█████████████▎          | 166/300 [01:25<01:09,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  56%|█████████████▎          | 167/300 [01:26<01:08,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  56%|█████████████▍          | 168/300 [01:26<01:10,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  56%|█████████████▌          | 169/300 [01:27<01:08,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  57%|█████████████▌          | 170/300 [01:27<01:07,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  57%|█████████████▋          | 171/300 [01:28<01:05,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  57%|█████████████▊          | 172/300 [01:28<01:07,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  58%|█████████████▊          | 173/300 [01:29<01:06,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  58%|█████████████▉          | 174/300 [01:29<01:04,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  58%|██████████████          | 175/300 [01:30<01:03,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  59%|██████████████          | 176/300 [01:30<01:08,  1.81it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  59%|██████████████▏         | 177/300 [01:31<01:05,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  59%|██████████████▏         | 178/300 [01:31<01:06,  1.82it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  60%|██████████████▎         | 179/300 [01:32<01:04,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  60%|██████████████▍         | 180/300 [01:32<01:02,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  60%|██████████████▍         | 181/300 [01:33<01:00,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  61%|██████████████▌         | 182/300 [01:33<00:59,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  61%|██████████████▋         | 183/300 [01:34<00:58,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  61%|██████████████▋         | 184/300 [01:34<00:58,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  62%|██████████████▊         | 185/300 [01:35<00:57,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  62%|██████████████▉         | 186/300 [01:35<00:57,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  62%|██████████████▉         | 187/300 [01:36<00:56,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  63%|███████████████         | 188/300 [01:36<00:58,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  63%|███████████████         | 189/300 [01:37<00:57,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  63%|███████████████▏        | 190/300 [01:37<00:56,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  64%|███████████████▎        | 191/300 [01:38<00:55,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  64%|███████████████▎        | 192/300 [01:38<00:54,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  64%|███████████████▍        | 193/300 [01:39<00:53,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  65%|███████████████▌        | 194/300 [01:39<00:52,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  65%|███████████████▌        | 195/300 [01:40<00:47,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  65%|███████████████▋        | 196/300 [01:40<00:53,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  66%|███████████████▊        | 197/300 [01:41<00:52,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  66%|███████████████▊        | 198/300 [01:41<00:51,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  66%|███████████████▉        | 199/300 [01:42<00:52,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  67%|████████████████        | 200/300 [01:42<00:51,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  67%|████████████████        | 201/300 [01:43<00:59,  1.67it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  67%|████████████████▏       | 202/300 [01:44<00:58,  1.68it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  68%|████████████████▏       | 203/300 [01:44<00:50,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  68%|████████████████▎       | 204/300 [01:45<00:48,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  68%|████████████████▍       | 205/300 [01:45<00:47,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  69%|████████████████▍       | 206/300 [01:45<00:42,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  69%|████████████████▌       | 207/300 [01:46<00:43,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  69%|████████████████▋       | 208/300 [01:46<00:43,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  70%|████████████████▋       | 209/300 [01:47<00:45,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  70%|████████████████▊       | 210/300 [01:48<00:45,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  70%|████████████████▉       | 211/300 [01:48<00:44,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  71%|████████████████▉       | 212/300 [01:49<00:46,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  71%|█████████████████       | 213/300 [01:49<00:40,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  71%|█████████████████       | 214/300 [01:50<00:43,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  72%|█████████████████▏      | 215/300 [01:50<00:42,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  72%|█████████████████▎      | 216/300 [01:51<00:41,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  72%|█████████████████▎      | 217/300 [01:51<00:45,  1.83it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  73%|█████████████████▍      | 218/300 [01:52<00:43,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  73%|█████████████████▌      | 219/300 [01:52<00:44,  1.81it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  73%|█████████████████▌      | 220/300 [01:53<00:44,  1.79it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  74%|█████████████████▋      | 221/300 [01:53<00:44,  1.77it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  74%|█████████████████▊      | 222/300 [01:54<00:42,  1.83it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  74%|█████████████████▊      | 223/300 [01:54<00:40,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  75%|█████████████████▉      | 224/300 [01:55<00:41,  1.83it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  75%|██████████████████      | 225/300 [01:56<00:39,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  75%|██████████████████      | 226/300 [01:56<00:34,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  76%|██████████████████▏     | 227/300 [01:56<00:34,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  76%|██████████████████▏     | 228/300 [01:57<00:36,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  76%|██████████████████▎     | 229/300 [01:57<00:35,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  77%|██████████████████▍     | 230/300 [01:58<00:35,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  77%|██████████████████▍     | 231/300 [01:58<00:34,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  77%|██████████████████▌     | 232/300 [01:59<00:33,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  78%|██████████████████▋     | 233/300 [01:59<00:33,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  78%|██████████████████▋     | 234/300 [02:00<00:32,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  78%|██████████████████▊     | 235/300 [02:00<00:32,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  79%|██████████████████▉     | 236/300 [02:01<00:31,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  79%|██████████████████▉     | 237/300 [02:01<00:31,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  79%|███████████████████     | 238/300 [02:02<00:30,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  80%|███████████████████     | 239/300 [02:02<00:30,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  80%|███████████████████▏    | 240/300 [02:03<00:30,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  80%|███████████████████▎    | 241/300 [02:04<00:32,  1.82it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  81%|███████████████████▎    | 242/300 [02:04<00:30,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  81%|███████████████████▍    | 243/300 [02:05<00:30,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  81%|███████████████████▌    | 244/300 [02:05<00:29,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  82%|███████████████████▌    | 245/300 [02:06<00:28,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  82%|███████████████████▋    | 246/300 [02:06<00:28,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  82%|███████████████████▊    | 247/300 [02:07<00:27,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  83%|███████████████████▊    | 248/300 [02:07<00:27,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  83%|███████████████████▉    | 249/300 [02:08<00:26,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  83%|████████████████████    | 250/300 [02:08<00:25,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  84%|████████████████████    | 251/300 [02:09<00:25,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  84%|████████████████████▏   | 252/300 [02:09<00:25,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  84%|████████████████████▏   | 253/300 [02:10<00:24,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  85%|████████████████████▎   | 254/300 [02:10<00:24,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  85%|████████████████████▍   | 255/300 [02:11<00:25,  1.74it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  85%|████████████████████▍   | 256/300 [02:11<00:24,  1.82it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  86%|████████████████████▌   | 257/300 [02:12<00:23,  1.79it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  86%|████████████████████▋   | 258/300 [02:13<00:22,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  86%|████████████████████▋   | 259/300 [02:13<00:21,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  87%|████████████████████▊   | 260/300 [02:14<00:20,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  87%|████████████████████▉   | 261/300 [02:14<00:19,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  87%|████████████████████▉   | 262/300 [02:15<00:20,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  88%|█████████████████████   | 263/300 [02:15<00:19,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  88%|█████████████████████   | 264/300 [02:16<00:19,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  88%|█████████████████████▏  | 265/300 [02:16<00:19,  1.82it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  89%|█████████████████████▎  | 266/300 [02:17<00:18,  1.79it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  89%|█████████████████████▎  | 267/300 [02:17<00:17,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  89%|█████████████████████▍  | 268/300 [02:18<00:16,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  90%|█████████████████████▌  | 269/300 [02:18<00:14,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  90%|█████████████████████▌  | 270/300 [02:19<00:14,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  90%|█████████████████████▋  | 271/300 [02:19<00:14,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  91%|█████████████████████▊  | 272/300 [02:20<00:13,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  91%|█████████████████████▊  | 273/300 [02:20<00:13,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  91%|█████████████████████▉  | 274/300 [02:21<00:12,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  92%|██████████████████████  | 275/300 [02:21<00:12,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  92%|██████████████████████  | 276/300 [02:22<00:12,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  92%|██████████████████████▏ | 277/300 [02:22<00:12,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  93%|██████████████████████▏ | 278/300 [02:23<00:10,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  93%|██████████████████████▎ | 279/300 [02:23<00:10,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  93%|██████████████████████▍ | 280/300 [02:24<00:10,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  94%|██████████████████████▍ | 281/300 [02:24<00:08,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  94%|██████████████████████▌ | 282/300 [02:25<00:08,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  94%|██████████████████████▋ | 283/300 [02:25<00:08,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  95%|██████████████████████▋ | 284/300 [02:26<00:07,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  95%|██████████████████████▊ | 285/300 [02:26<00:06,  2.27it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  95%|██████████████████████▉ | 286/300 [02:26<00:06,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  96%|██████████████████████▉ | 287/300 [02:27<00:05,  2.38it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  96%|███████████████████████ | 288/300 [02:27<00:05,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  96%|███████████████████████ | 289/300 [02:28<00:05,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  97%|███████████████████████▏| 290/300 [02:28<00:04,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  97%|███████████████████████▎| 291/300 [02:29<00:04,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  97%|███████████████████████▎| 292/300 [02:29<00:04,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  98%|███████████████████████▍| 293/300 [02:30<00:03,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  98%|███████████████████████▌| 294/300 [02:30<00:03,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  98%|███████████████████████▌| 295/300 [02:31<00:02,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  99%|███████████████████████▋| 296/300 [02:32<00:02,  1.77it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  99%|███████████████████████▊| 297/300 [02:32<00:01,  1.83it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5:  99%|███████████████████████▊| 298/300 [02:33<00:01,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5: 100%|███████████████████████▉| 299/300 [02:33<00:00,  1.84it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.5: 100%|████████████████████████| 300/300 [02:34<00:00,  1.89it/s]
Steering Strength:  20%|████▌                  | 1/5 [02:34<10:16, 154.24s/it]
Strength -0.2:   0%|                                  | 0/300 [00:00<?, ?it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   0%|                          | 1/300 [00:00<02:32,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   1%|▏                         | 2/300 [00:01<02:44,  1.81it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   1%|▎                         | 3/300 [00:01<02:47,  1.78it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   1%|▎                         | 4/300 [00:02<02:39,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   2%|▍                         | 5/300 [00:02<02:25,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   2%|▌                         | 6/300 [00:03<02:17,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   2%|▌                         | 7/300 [00:03<02:19,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   3%|▋                         | 8/300 [00:04<02:29,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   3%|▊                         | 9/300 [00:04<02:43,  1.78it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   3%|▊                        | 10/300 [00:05<02:44,  1.77it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   4%|▉                        | 11/300 [00:05<02:45,  1.75it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   4%|█                        | 12/300 [00:06<02:30,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   4%|█                        | 13/300 [00:06<02:20,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   5%|█▏                       | 14/300 [00:07<02:13,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   5%|█▎                       | 15/300 [00:07<02:08,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   5%|█▎                       | 16/300 [00:08<02:19,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   6%|█▍                       | 17/300 [00:08<02:11,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   6%|█▌                       | 18/300 [00:08<02:07,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   6%|█▌                       | 19/300 [00:09<02:03,  2.27it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   7%|█▋                       | 20/300 [00:09<02:07,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   7%|█▊                       | 21/300 [00:10<02:11,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   7%|█▊                       | 22/300 [00:10<02:12,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   8%|█▉                       | 23/300 [00:11<02:20,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   8%|██                       | 24/300 [00:12<02:25,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   8%|██                       | 25/300 [00:12<02:15,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   9%|██▏                      | 26/300 [00:13<02:28,  1.84it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   9%|██▎                      | 27/300 [00:13<02:17,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:   9%|██▎                      | 28/300 [00:14<02:16,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  10%|██▍                      | 29/300 [00:14<02:28,  1.82it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  10%|██▌                      | 30/300 [00:15<02:37,  1.72it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  10%|██▌                      | 31/300 [00:15<02:36,  1.72it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  11%|██▋                      | 32/300 [00:16<02:22,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  11%|██▊                      | 33/300 [00:16<02:12,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  11%|██▊                      | 34/300 [00:17<02:12,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  12%|██▉                      | 35/300 [00:17<02:18,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  12%|███                      | 36/300 [00:18<02:15,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  12%|███                      | 37/300 [00:18<02:13,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  13%|███▏                     | 38/300 [00:19<02:06,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  13%|███▎                     | 39/300 [00:19<02:00,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  13%|███▎                     | 40/300 [00:20<01:56,  2.24it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  14%|███▍                     | 41/300 [00:20<01:52,  2.29it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  14%|███▌                     | 42/300 [00:21<02:03,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  14%|███▌                     | 43/300 [00:21<02:10,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  15%|███▋                     | 44/300 [00:22<02:28,  1.72it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  15%|███▊                     | 45/300 [00:22<02:15,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  15%|███▊                     | 46/300 [00:23<02:05,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  16%|███▉                     | 47/300 [00:23<01:58,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  16%|████                     | 48/300 [00:24<01:54,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  16%|████                     | 49/300 [00:24<01:51,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  17%|████▏                    | 50/300 [00:24<01:49,  2.28it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  17%|████▎                    | 51/300 [00:25<01:47,  2.31it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  17%|████▎                    | 52/300 [00:25<01:45,  2.35it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  18%|████▍                    | 53/300 [00:26<01:56,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  18%|████▌                    | 54/300 [00:26<01:57,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  18%|████▌                    | 55/300 [00:27<01:58,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  19%|████▋                    | 56/300 [00:27<01:52,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  19%|████▊                    | 57/300 [00:28<02:01,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  19%|████▊                    | 58/300 [00:28<02:13,  1.81it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  20%|████▉                    | 59/300 [00:29<02:21,  1.71it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  20%|█████                    | 60/300 [00:30<02:08,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  20%|█████                    | 61/300 [00:30<02:05,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  21%|█████▏                   | 62/300 [00:31<02:03,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  21%|█████▎                   | 63/300 [00:31<01:58,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  21%|█████▎                   | 64/300 [00:31<01:57,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  22%|█████▍                   | 65/300 [00:32<01:50,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  22%|█████▌                   | 66/300 [00:32<01:57,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  22%|█████▌                   | 67/300 [00:33<01:50,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  23%|█████▋                   | 68/300 [00:33<01:52,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  23%|█████▊                   | 69/300 [00:34<01:58,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  23%|█████▊                   | 70/300 [00:34<01:51,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  24%|█████▉                   | 71/300 [00:35<01:57,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  24%|██████                   | 72/300 [00:36<02:06,  1.80it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  24%|██████                   | 73/300 [00:36<02:02,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  25%|██████▏                  | 74/300 [00:37<02:04,  1.81it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  25%|██████▎                  | 75/300 [00:37<01:54,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  25%|██████▎                  | 76/300 [00:38<01:47,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  26%|██████▍                  | 77/300 [00:38<01:54,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  26%|██████▌                  | 78/300 [00:39<01:58,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  26%|██████▌                  | 79/300 [00:39<02:00,  1.84it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  27%|██████▋                  | 80/300 [00:40<01:56,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  27%|██████▊                  | 81/300 [00:40<01:48,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  27%|██████▊                  | 82/300 [00:41<01:43,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  28%|██████▉                  | 83/300 [00:41<01:38,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  28%|███████                  | 84/300 [00:41<01:35,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  28%|███████                  | 85/300 [00:42<01:33,  2.30it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  29%|███████▏                 | 86/300 [00:42<01:31,  2.34it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  29%|███████▏                 | 87/300 [00:43<01:40,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  29%|███████▎                 | 88/300 [00:43<01:36,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  30%|███████▍                 | 89/300 [00:44<01:39,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  30%|███████▌                 | 90/300 [00:44<01:34,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  30%|███████▌                 | 91/300 [00:45<01:31,  2.27it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  31%|███████▋                 | 92/300 [00:45<01:35,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  31%|███████▊                 | 93/300 [00:45<01:31,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  31%|███████▊                 | 94/300 [00:46<01:29,  2.30it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  32%|███████▉                 | 95/300 [00:46<01:27,  2.34it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  32%|████████                 | 96/300 [00:47<01:41,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  32%|████████                 | 97/300 [00:47<01:36,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  33%|████████▏                | 98/300 [00:48<01:42,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  33%|████████▎                | 99/300 [00:49<01:45,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  33%|████████                | 100/300 [00:49<01:43,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  34%|████████                | 101/300 [00:50<01:42,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  34%|████████▏               | 102/300 [00:50<01:35,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  34%|████████▏               | 103/300 [00:51<01:45,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  35%|████████▎               | 104/300 [00:51<01:42,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  35%|████████▍               | 105/300 [00:52<01:45,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  35%|████████▍               | 106/300 [00:52<01:42,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  36%|████████▌               | 107/300 [00:53<01:35,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  36%|████████▋               | 108/300 [00:53<01:34,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  36%|████████▋               | 109/300 [00:54<01:34,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  37%|████████▊               | 110/300 [00:54<01:38,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  37%|████████▉               | 111/300 [00:55<01:41,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  37%|████████▉               | 112/300 [00:55<01:47,  1.74it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  38%|█████████               | 113/300 [00:56<01:38,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  38%|█████████               | 114/300 [00:56<01:45,  1.77it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  38%|█████████▏              | 115/300 [00:57<01:36,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  39%|█████████▎              | 116/300 [00:58<01:43,  1.78it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  39%|█████████▎              | 117/300 [00:58<01:34,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  39%|█████████▍              | 118/300 [00:59<01:37,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  40%|█████████▌              | 119/300 [00:59<01:30,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  40%|█████████▌              | 120/300 [00:59<01:25,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  40%|█████████▋              | 121/300 [01:00<01:21,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  41%|█████████▊              | 122/300 [01:00<01:22,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  41%|█████████▊              | 123/300 [01:01<01:19,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  41%|█████████▉              | 124/300 [01:01<01:21,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  42%|██████████              | 125/300 [01:02<01:18,  2.23it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  42%|██████████              | 126/300 [01:02<01:24,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  42%|██████████▏             | 127/300 [01:03<01:20,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  43%|██████████▏             | 128/300 [01:03<01:25,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  43%|██████████▎             | 129/300 [01:04<01:24,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  43%|██████████▍             | 130/300 [01:04<01:24,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  44%|██████████▍             | 131/300 [01:05<01:19,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  44%|██████████▌             | 132/300 [01:05<01:16,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  44%|██████████▋             | 133/300 [01:05<01:14,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  45%|██████████▋             | 134/300 [01:06<01:16,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  45%|██████████▊             | 135/300 [01:06<01:17,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  45%|██████████▉             | 136/300 [01:07<01:14,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  46%|██████████▉             | 137/300 [01:07<01:12,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  46%|███████████             | 138/300 [01:08<01:14,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  46%|███████████             | 139/300 [01:08<01:19,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  47%|███████████▏            | 140/300 [01:09<01:17,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  47%|███████████▎            | 141/300 [01:09<01:17,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  47%|███████████▎            | 142/300 [01:10<01:14,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  48%|███████████▍            | 143/300 [01:10<01:11,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  48%|███████████▌            | 144/300 [01:11<01:20,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  48%|███████████▌            | 145/300 [01:11<01:15,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  49%|███████████▋            | 146/300 [01:12<01:15,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  49%|███████████▊            | 147/300 [01:12<01:18,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  49%|███████████▊            | 148/300 [01:13<01:17,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  50%|███████████▉            | 149/300 [01:13<01:16,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  50%|████████████            | 150/300 [01:14<01:19,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  50%|████████████            | 151/300 [01:14<01:13,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  51%|████████████▏           | 152/300 [01:15<01:13,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  51%|████████████▏           | 153/300 [01:15<01:07,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  51%|████████████▎           | 154/300 [01:16<01:12,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  52%|████████████▍           | 155/300 [01:16<01:11,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  52%|████████████▍           | 156/300 [01:17<01:07,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  52%|████████████▌           | 157/300 [01:17<01:08,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  53%|████████████▋           | 158/300 [01:17<01:05,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  53%|████████████▋           | 159/300 [01:18<01:02,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  53%|████████████▊           | 160/300 [01:18<01:01,  2.29it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  54%|████████████▉           | 161/300 [01:19<01:03,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  54%|████████████▉           | 162/300 [01:19<01:04,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  54%|█████████████           | 163/300 [01:20<01:02,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  55%|█████████████           | 164/300 [01:20<01:07,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  55%|█████████████▏          | 165/300 [01:21<01:10,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  55%|█████████████▎          | 166/300 [01:21<01:05,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  56%|█████████████▎          | 167/300 [01:22<01:01,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  56%|█████████████▍          | 168/300 [01:22<01:02,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  56%|█████████████▌          | 169/300 [01:23<00:59,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  57%|█████████████▌          | 170/300 [01:23<01:01,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  57%|█████████████▋          | 171/300 [01:24<00:58,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  57%|█████████████▊          | 172/300 [01:24<01:02,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  58%|█████████████▊          | 173/300 [01:25<00:59,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  58%|█████████████▉          | 174/300 [01:25<00:56,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  58%|██████████████          | 175/300 [01:25<00:54,  2.28it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  59%|██████████████          | 176/300 [01:26<01:02,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  59%|██████████████▏         | 177/300 [01:26<00:58,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  59%|██████████████▏         | 178/300 [01:27<01:01,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  60%|██████████████▎         | 179/300 [01:27<00:57,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  60%|██████████████▍         | 180/300 [01:28<00:55,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  60%|██████████████▍         | 181/300 [01:28<00:51,  2.29it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  61%|██████████████▌         | 182/300 [01:29<00:51,  2.31it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  61%|██████████████▋         | 183/300 [01:29<00:55,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  61%|██████████████▋         | 184/300 [01:30<00:58,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  62%|██████████████▊         | 185/300 [01:30<00:54,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  62%|██████████████▉         | 186/300 [01:31<00:57,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  62%|██████████████▉         | 187/300 [01:31<00:54,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  63%|███████████████         | 188/300 [01:32<00:56,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  63%|███████████████         | 189/300 [01:32<00:53,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  63%|███████████████▏        | 190/300 [01:33<00:55,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  64%|███████████████▎        | 191/300 [01:33<00:54,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  64%|███████████████▎        | 192/300 [01:34<00:51,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  64%|███████████████▍        | 193/300 [01:34<00:48,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  65%|███████████████▌        | 194/300 [01:34<00:46,  2.27it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  65%|███████████████▌        | 195/300 [01:35<00:50,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  65%|███████████████▋        | 196/300 [01:36<00:55,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  66%|███████████████▊        | 197/300 [01:36<00:51,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  66%|███████████████▊        | 198/300 [01:37<00:53,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  66%|███████████████▉        | 199/300 [01:37<00:54,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  67%|████████████████        | 200/300 [01:38<00:49,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  67%|████████████████        | 201/300 [01:38<00:55,  1.78it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  67%|████████████████▏       | 202/300 [01:39<00:58,  1.69it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  68%|████████████████▏       | 203/300 [01:40<00:54,  1.77it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  68%|████████████████▎       | 204/300 [01:40<00:49,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  68%|████████████████▍       | 205/300 [01:40<00:46,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  69%|████████████████▍       | 206/300 [01:41<00:48,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  69%|████████████████▌       | 207/300 [01:42<00:49,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  69%|████████████████▋       | 208/300 [01:42<00:47,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  70%|████████████████▋       | 209/300 [01:43<00:46,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  70%|████████████████▊       | 210/300 [01:43<00:45,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  70%|████████████████▉       | 211/300 [01:43<00:42,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  71%|████████████████▉       | 212/300 [01:44<00:42,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  71%|█████████████████       | 213/300 [01:44<00:44,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  71%|█████████████████       | 214/300 [01:45<00:45,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  72%|█████████████████▏      | 215/300 [01:46<00:46,  1.83it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  72%|█████████████████▎      | 216/300 [01:46<00:44,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  72%|█████████████████▎      | 217/300 [01:47<00:47,  1.77it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  73%|█████████████████▍      | 218/300 [01:47<00:44,  1.84it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  73%|█████████████████▌      | 219/300 [01:48<00:41,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  73%|█████████████████▌      | 220/300 [01:48<00:42,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  74%|█████████████████▋      | 221/300 [01:49<00:40,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  74%|█████████████████▊      | 222/300 [01:49<00:41,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  74%|█████████████████▊      | 223/300 [01:50<00:38,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  75%|█████████████████▉      | 224/300 [01:50<00:37,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  75%|██████████████████      | 225/300 [01:51<00:35,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  75%|██████████████████      | 226/300 [01:51<00:36,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  76%|██████████████████▏     | 227/300 [01:52<00:34,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  76%|██████████████████▏     | 228/300 [01:52<00:36,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  76%|██████████████████▎     | 229/300 [01:53<00:33,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  77%|██████████████████▍     | 230/300 [01:53<00:31,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  77%|██████████████████▍     | 231/300 [01:53<00:30,  2.28it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  77%|██████████████████▌     | 232/300 [01:54<00:32,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  78%|██████████████████▋     | 233/300 [01:55<00:32,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  78%|██████████████████▋     | 234/300 [01:55<00:32,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  78%|██████████████████▊     | 235/300 [01:56<00:33,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  79%|██████████████████▉     | 236/300 [01:56<00:32,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  79%|██████████████████▉     | 237/300 [01:56<00:29,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  79%|███████████████████     | 238/300 [01:57<00:28,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  80%|███████████████████     | 239/300 [01:58<00:31,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  80%|███████████████████▏    | 240/300 [01:58<00:32,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  80%|███████████████████▎    | 241/300 [01:59<00:33,  1.75it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  81%|███████████████████▎    | 242/300 [01:59<00:30,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  81%|███████████████████▍    | 243/300 [02:00<00:30,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  81%|███████████████████▌    | 244/300 [02:00<00:29,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  82%|███████████████████▌    | 245/300 [02:01<00:28,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  82%|███████████████████▋    | 246/300 [02:01<00:28,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  82%|███████████████████▊    | 247/300 [02:02<00:27,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  83%|███████████████████▊    | 248/300 [02:02<00:26,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  83%|███████████████████▉    | 249/300 [02:03<00:24,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  83%|████████████████████    | 250/300 [02:03<00:23,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  84%|████████████████████    | 251/300 [02:04<00:24,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  84%|████████████████████▏   | 252/300 [02:04<00:23,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  84%|████████████████████▏   | 253/300 [02:05<00:27,  1.70it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  85%|████████████████████▎   | 254/300 [02:05<00:25,  1.78it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  85%|████████████████████▍   | 255/300 [02:06<00:26,  1.70it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  85%|████████████████████▍   | 256/300 [02:07<00:23,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  86%|████████████████████▌   | 257/300 [02:07<00:23,  1.82it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  86%|████████████████████▋   | 258/300 [02:08<00:22,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  86%|████████████████████▋   | 259/300 [02:08<00:20,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  87%|████████████████████▊   | 260/300 [02:08<00:18,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  87%|████████████████████▉   | 261/300 [02:09<00:17,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  87%|████████████████████▉   | 262/300 [02:09<00:18,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  88%|█████████████████████   | 263/300 [02:10<00:17,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  88%|█████████████████████   | 264/300 [02:10<00:17,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  88%|█████████████████████▏  | 265/300 [02:11<00:19,  1.83it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  89%|█████████████████████▎  | 266/300 [02:12<00:18,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  89%|█████████████████████▎  | 267/300 [02:12<00:17,  1.84it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  89%|█████████████████████▍  | 268/300 [02:13<00:16,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  90%|█████████████████████▌  | 269/300 [02:13<00:16,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  90%|█████████████████████▌  | 270/300 [02:14<00:16,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  90%|█████████████████████▋  | 271/300 [02:14<00:14,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  91%|█████████████████████▊  | 272/300 [02:15<00:14,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  91%|█████████████████████▊  | 273/300 [02:15<00:12,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  91%|█████████████████████▉  | 274/300 [02:16<00:12,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  92%|██████████████████████  | 275/300 [02:16<00:11,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  92%|██████████████████████  | 276/300 [02:16<00:11,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  92%|██████████████████████▏ | 277/300 [02:17<00:11,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  93%|██████████████████████▏ | 278/300 [02:17<00:10,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  93%|██████████████████████▎ | 279/300 [02:18<00:09,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  93%|██████████████████████▍ | 280/300 [02:18<00:09,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  94%|██████████████████████▍ | 281/300 [02:19<00:10,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  94%|██████████████████████▌ | 282/300 [02:20<00:09,  1.82it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  94%|██████████████████████▋ | 283/300 [02:20<00:08,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  95%|██████████████████████▋ | 284/300 [02:20<00:07,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  95%|██████████████████████▊ | 285/300 [02:21<00:06,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  95%|██████████████████████▉ | 286/300 [02:21<00:06,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  96%|██████████████████████▉ | 287/300 [02:22<00:06,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  96%|███████████████████████ | 288/300 [02:22<00:05,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  96%|███████████████████████ | 289/300 [02:23<00:05,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  97%|███████████████████████▏| 290/300 [02:23<00:04,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  97%|███████████████████████▎| 291/300 [02:24<00:04,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  97%|███████████████████████▎| 292/300 [02:24<00:03,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  98%|███████████████████████▍| 293/300 [02:25<00:03,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  98%|███████████████████████▌| 294/300 [02:25<00:02,  2.28it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  98%|███████████████████████▌| 295/300 [02:26<00:02,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  99%|███████████████████████▋| 296/300 [02:26<00:01,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  99%|███████████████████████▊| 297/300 [02:27<00:01,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2:  99%|███████████████████████▊| 298/300 [02:27<00:00,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2: 100%|███████████████████████▉| 299/300 [02:28<00:00,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.2: 100%|████████████████████████| 300/300 [02:28<00:00,  2.15it/s]
Steering Strength:  40%|█████████▏             | 2/5 [05:02<07:32, 150.83s/it]
Strength -0.1:   0%|                                  | 0/300 [00:00<?, ?it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   0%|                          | 1/300 [00:00<02:27,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   1%|▏                         | 2/300 [00:00<02:27,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   1%|▎                         | 3/300 [00:01<02:27,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   1%|▎                         | 4/300 [00:01<02:26,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   2%|▍                         | 5/300 [00:02<02:34,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   2%|▌                         | 6/300 [00:02<02:24,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   2%|▌                         | 7/300 [00:03<02:16,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   3%|▋                         | 8/300 [00:03<02:26,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   3%|▊                         | 9/300 [00:04<02:41,  1.80it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   3%|▊                        | 10/300 [00:05<02:42,  1.78it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   4%|▉                        | 11/300 [00:05<02:44,  1.76it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   4%|█                        | 12/300 [00:06<02:29,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   4%|█                        | 13/300 [00:06<02:19,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   5%|█▏                       | 14/300 [00:07<02:12,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   5%|█▎                       | 15/300 [00:07<02:08,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   5%|█▎                       | 16/300 [00:08<02:18,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   6%|█▍                       | 17/300 [00:08<02:11,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   6%|█▌                       | 18/300 [00:08<02:07,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   6%|█▌                       | 19/300 [00:09<02:03,  2.27it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   7%|█▋                       | 20/300 [00:09<02:07,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   7%|█▊                       | 21/300 [00:10<02:10,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   7%|█▊                       | 22/300 [00:10<02:12,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   8%|█▉                       | 23/300 [00:11<02:13,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   8%|██                       | 24/300 [00:11<02:13,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   8%|██                       | 25/300 [00:12<02:07,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   9%|██▏                      | 26/300 [00:12<02:22,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   9%|██▎                      | 27/300 [00:13<02:13,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:   9%|██▎                      | 28/300 [00:13<02:13,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  10%|██▍                      | 29/300 [00:14<02:26,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  10%|██▌                      | 30/300 [00:15<02:35,  1.73it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  10%|██▌                      | 31/300 [00:15<02:35,  1.73it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  11%|██▋                      | 32/300 [00:16<02:21,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  11%|██▊                      | 33/300 [00:16<02:11,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  11%|██▊                      | 34/300 [00:16<02:12,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  12%|██▉                      | 35/300 [00:17<02:11,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  12%|███                      | 36/300 [00:17<02:04,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  12%|███                      | 37/300 [00:18<01:59,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  13%|███▏                     | 38/300 [00:18<01:56,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  13%|███▎                     | 39/300 [00:19<01:53,  2.30it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  13%|███▎                     | 40/300 [00:19<01:51,  2.34it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  14%|███▍                     | 41/300 [00:19<01:49,  2.37it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  14%|███▌                     | 42/300 [00:20<02:00,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  14%|███▌                     | 43/300 [00:21<02:08,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  15%|███▋                     | 44/300 [00:21<02:27,  1.74it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  15%|███▊                     | 45/300 [00:22<02:14,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  15%|███▊                     | 46/300 [00:22<02:04,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  16%|███▉                     | 47/300 [00:23<01:58,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  16%|████                     | 48/300 [00:23<01:54,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  16%|████                     | 49/300 [00:23<01:51,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  17%|████▏                    | 50/300 [00:24<01:49,  2.29it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  17%|████▎                    | 51/300 [00:24<01:48,  2.31it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  17%|████▎                    | 52/300 [00:25<01:45,  2.35it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  18%|████▍                    | 53/300 [00:25<01:56,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  18%|████▌                    | 54/300 [00:26<01:57,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  18%|████▌                    | 55/300 [00:26<01:58,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  19%|████▋                    | 56/300 [00:27<01:52,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  19%|████▊                    | 57/300 [00:27<02:01,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  19%|████▊                    | 58/300 [00:28<02:13,  1.81it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  20%|████▉                    | 59/300 [00:28<02:15,  1.78it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  20%|█████                    | 60/300 [00:29<02:04,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  20%|█████                    | 61/300 [00:29<02:02,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  21%|█████▏                   | 62/300 [00:30<01:54,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  21%|█████▎                   | 63/300 [00:30<01:46,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  21%|█████▎                   | 64/300 [00:31<01:43,  2.28it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  22%|█████▍                   | 65/300 [00:31<01:41,  2.32it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  22%|█████▌                   | 66/300 [00:32<01:50,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  22%|█████▌                   | 67/300 [00:32<01:46,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  23%|█████▋                   | 68/300 [00:32<01:42,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  23%|█████▊                   | 69/300 [00:33<01:51,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  23%|█████▊                   | 70/300 [00:33<01:47,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  24%|█████▉                   | 71/300 [00:34<01:54,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  24%|██████                   | 72/300 [00:35<02:04,  1.83it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  24%|██████                   | 73/300 [00:35<01:54,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  25%|██████▏                  | 74/300 [00:35<01:48,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  25%|██████▎                  | 75/300 [00:36<01:43,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  25%|██████▎                  | 76/300 [00:36<01:39,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  26%|██████▍                  | 77/300 [00:37<01:48,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  26%|██████▌                  | 78/300 [00:37<01:47,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  26%|██████▌                  | 79/300 [00:38<01:47,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  27%|██████▋                  | 80/300 [00:38<01:47,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  27%|██████▊                  | 81/300 [00:39<01:41,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  27%|██████▊                  | 82/300 [00:39<01:38,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  28%|██████▉                  | 83/300 [00:40<01:34,  2.29it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  28%|███████                  | 84/300 [00:40<01:32,  2.34it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  28%|███████                  | 85/300 [00:40<01:30,  2.37it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  29%|███████▏                 | 86/300 [00:41<01:29,  2.40it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  29%|███████▏                 | 87/300 [00:41<01:33,  2.28it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  29%|███████▎                 | 88/300 [00:42<01:30,  2.33it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  30%|███████▍                 | 89/300 [00:42<01:35,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  30%|███████▌                 | 90/300 [00:43<01:31,  2.29it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  30%|███████▌                 | 91/300 [00:43<01:29,  2.34it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  31%|███████▋                 | 92/300 [00:43<01:27,  2.37it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  31%|███████▊                 | 93/300 [00:44<01:26,  2.39it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  31%|███████▊                 | 94/300 [00:44<01:25,  2.41it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  32%|███████▉                 | 95/300 [00:45<01:24,  2.43it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  32%|████████                 | 96/300 [00:45<01:38,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  32%|████████                 | 97/300 [00:46<01:34,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  33%|████████▏                | 98/300 [00:46<01:40,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  33%|████████▎                | 99/300 [00:47<01:39,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  33%|████████                | 100/300 [00:47<01:33,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  34%|████████                | 101/300 [00:48<01:30,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  34%|████████▏               | 102/300 [00:48<01:27,  2.28it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  34%|████████▏               | 103/300 [00:49<01:39,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  35%|████████▎               | 104/300 [00:49<01:37,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  35%|████████▍               | 105/300 [00:50<01:41,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  35%|████████▍               | 106/300 [00:50<01:39,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  36%|████████▌               | 107/300 [00:51<01:32,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  36%|████████▋               | 108/300 [00:51<01:33,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  36%|████████▋               | 109/300 [00:52<01:37,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  37%|████████▊               | 110/300 [00:52<01:35,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  37%|████████▉               | 111/300 [00:53<01:34,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  37%|████████▉               | 112/300 [00:53<01:42,  1.83it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  38%|█████████               | 113/300 [00:54<01:39,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  38%|█████████               | 114/300 [00:54<01:45,  1.77it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  38%|█████████▏              | 115/300 [00:55<01:36,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  39%|█████████▎              | 116/300 [00:56<01:42,  1.79it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  39%|█████████▎              | 117/300 [00:56<01:33,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  39%|█████████▍              | 118/300 [00:57<01:36,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  40%|█████████▌              | 119/300 [00:57<01:29,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  40%|█████████▌              | 120/300 [00:57<01:24,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  40%|█████████▋              | 121/300 [00:58<01:20,  2.23it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  41%|█████████▊              | 122/300 [00:58<01:22,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  41%|█████████▊              | 123/300 [00:59<01:18,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  41%|█████████▉              | 124/300 [00:59<01:16,  2.31it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  42%|██████████              | 125/300 [00:59<01:14,  2.35it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  42%|██████████              | 126/300 [01:00<01:17,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  42%|██████████▏             | 127/300 [01:00<01:14,  2.31it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  43%|██████████▏             | 128/300 [01:01<01:21,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  43%|██████████▎             | 129/300 [01:01<01:21,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  43%|██████████▍             | 130/300 [01:02<01:17,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  44%|██████████▍             | 131/300 [01:02<01:14,  2.27it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  44%|██████████▌             | 132/300 [01:03<01:12,  2.32it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  44%|██████████▋             | 133/300 [01:03<01:11,  2.34it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  45%|██████████▋             | 134/300 [01:04<01:14,  2.24it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  45%|██████████▊             | 135/300 [01:04<01:15,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  45%|██████████▉             | 136/300 [01:04<01:12,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  46%|██████████▉             | 137/300 [01:05<01:10,  2.30it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  46%|███████████             | 138/300 [01:05<01:13,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  46%|███████████             | 139/300 [01:06<01:14,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  47%|███████████▏            | 140/300 [01:06<01:13,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  47%|███████████▎            | 141/300 [01:07<01:14,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  47%|███████████▎            | 142/300 [01:07<01:12,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  48%|███████████▍            | 143/300 [01:08<01:09,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  48%|███████████▌            | 144/300 [01:08<01:19,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  48%|███████████▌            | 145/300 [01:09<01:14,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  49%|███████████▋            | 146/300 [01:09<01:14,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  49%|███████████▊            | 147/300 [01:10<01:18,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  49%|███████████▊            | 148/300 [01:10<01:17,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  50%|███████████▉            | 149/300 [01:11<01:19,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  50%|████████████            | 150/300 [01:11<01:17,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  50%|████████████            | 151/300 [01:12<01:12,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  51%|████████████▏           | 152/300 [01:12<01:09,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  51%|████████████▏           | 153/300 [01:13<01:04,  2.27it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  51%|████████████▎           | 154/300 [01:13<01:10,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  52%|████████████▍           | 155/300 [01:14<01:10,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  52%|████████████▍           | 156/300 [01:14<01:06,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  52%|████████████▌           | 157/300 [01:15<01:07,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  53%|████████████▋           | 158/300 [01:15<01:08,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  53%|████████████▋           | 159/300 [01:15<01:04,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  53%|████████████▊           | 160/300 [01:16<01:02,  2.24it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  54%|████████████▉           | 161/300 [01:16<01:04,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  54%|████████████▉           | 162/300 [01:17<01:08,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  54%|█████████████           | 163/300 [01:17<01:05,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  55%|█████████████           | 164/300 [01:18<01:05,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  55%|█████████████▏          | 165/300 [01:18<01:05,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  55%|█████████████▎          | 166/300 [01:19<01:02,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  56%|█████████████▎          | 167/300 [01:19<00:59,  2.23it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  56%|█████████████▍          | 168/300 [01:20<01:00,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  56%|█████████████▌          | 169/300 [01:20<00:58,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  57%|█████████████▌          | 170/300 [01:20<00:57,  2.27it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  57%|█████████████▋          | 171/300 [01:21<00:55,  2.32it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  57%|█████████████▊          | 172/300 [01:21<01:00,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  58%|█████████████▊          | 173/300 [01:22<00:57,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  58%|█████████████▉          | 174/300 [01:22<00:55,  2.27it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  58%|██████████████          | 175/300 [01:23<00:53,  2.33it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  59%|██████████████          | 176/300 [01:23<01:01,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  59%|██████████████▏         | 177/300 [01:24<00:57,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  59%|██████████████▏         | 178/300 [01:24<00:58,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  60%|██████████████▎         | 179/300 [01:25<00:55,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  60%|██████████████▍         | 180/300 [01:25<00:53,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  60%|██████████████▍         | 181/300 [01:25<00:50,  2.37it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  61%|██████████████▌         | 182/300 [01:26<00:49,  2.37it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  61%|██████████████▋         | 183/300 [01:26<00:54,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  61%|██████████████▋         | 184/300 [01:27<00:54,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  62%|██████████████▊         | 185/300 [01:27<00:52,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  62%|██████████████▉         | 186/300 [01:28<00:56,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  62%|██████████████▉         | 187/300 [01:28<00:52,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  63%|███████████████         | 188/300 [01:29<00:55,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  63%|███████████████         | 189/300 [01:29<00:52,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  63%|███████████████▏        | 190/300 [01:30<00:55,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  64%|███████████████▎        | 191/300 [01:30<00:51,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  64%|███████████████▎        | 192/300 [01:31<00:49,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  64%|███████████████▍        | 193/300 [01:31<00:47,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  65%|███████████████▌        | 194/300 [01:32<00:45,  2.32it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  65%|███████████████▌        | 195/300 [01:32<00:50,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  65%|███████████████▋        | 196/300 [01:33<00:54,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  66%|███████████████▊        | 197/300 [01:33<00:50,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  66%|███████████████▊        | 198/300 [01:34<00:52,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  66%|███████████████▉        | 199/300 [01:34<00:51,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  67%|████████████████        | 200/300 [01:35<00:47,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  67%|████████████████        | 201/300 [01:35<00:53,  1.83it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  67%|████████████████▏       | 202/300 [01:36<00:56,  1.73it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  68%|████████████████▏       | 203/300 [01:36<00:53,  1.81it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  68%|████████████████▎       | 204/300 [01:37<00:48,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  68%|████████████████▍       | 205/300 [01:37<00:45,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  69%|████████████████▍       | 206/300 [01:38<00:45,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  69%|████████████████▌       | 207/300 [01:38<00:42,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  69%|████████████████▋       | 208/300 [01:39<00:45,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  70%|████████████████▋       | 209/300 [01:39<00:44,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  70%|████████████████▊       | 210/300 [01:40<00:42,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  70%|████████████████▉       | 211/300 [01:40<00:39,  2.23it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  71%|████████████████▉       | 212/300 [01:41<00:41,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  71%|█████████████████       | 213/300 [01:41<00:43,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  71%|█████████████████       | 214/300 [01:42<00:45,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  72%|█████████████████▏      | 215/300 [01:42<00:45,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  72%|█████████████████▎      | 216/300 [01:43<00:44,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  72%|█████████████████▎      | 217/300 [01:43<00:46,  1.77it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  73%|█████████████████▍      | 218/300 [01:44<00:42,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  73%|█████████████████▌      | 219/300 [01:44<00:39,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  73%|█████████████████▌      | 220/300 [01:45<00:41,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  74%|█████████████████▋      | 221/300 [01:45<00:40,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  74%|█████████████████▊      | 222/300 [01:46<00:41,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  74%|█████████████████▊      | 223/300 [01:46<00:37,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  75%|█████████████████▉      | 224/300 [01:47<00:37,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  75%|██████████████████      | 225/300 [01:47<00:35,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  75%|██████████████████      | 226/300 [01:48<00:37,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  76%|██████████████████▏     | 227/300 [01:48<00:34,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  76%|██████████████████▏     | 228/300 [01:49<00:36,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  76%|██████████████████▎     | 229/300 [01:49<00:33,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  77%|██████████████████▍     | 230/300 [01:50<00:32,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  77%|██████████████████▍     | 231/300 [01:50<00:30,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  77%|██████████████████▌     | 232/300 [01:51<00:32,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  78%|██████████████████▋     | 233/300 [01:51<00:30,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  78%|██████████████████▋     | 234/300 [01:51<00:29,  2.24it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  78%|██████████████████▊     | 235/300 [01:52<00:31,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  79%|██████████████████▉     | 236/300 [01:52<00:29,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  79%|██████████████████▉     | 237/300 [01:53<00:28,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  79%|███████████████████     | 238/300 [01:53<00:26,  2.31it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  80%|███████████████████     | 239/300 [01:54<00:30,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  80%|███████████████████▏    | 240/300 [01:54<00:31,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  80%|███████████████████▎    | 241/300 [01:55<00:33,  1.77it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  81%|███████████████████▎    | 242/300 [01:56<00:30,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  81%|███████████████████▍    | 243/300 [01:56<00:29,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  81%|███████████████████▌    | 244/300 [01:57<00:27,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  82%|███████████████████▌    | 245/300 [01:57<00:25,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  82%|███████████████████▋    | 246/300 [01:57<00:27,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  82%|███████████████████▊    | 247/300 [01:58<00:25,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  83%|███████████████████▊    | 248/300 [01:58<00:24,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  83%|███████████████████▉    | 249/300 [01:59<00:23,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  83%|████████████████████    | 250/300 [01:59<00:22,  2.24it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  84%|████████████████████    | 251/300 [02:00<00:23,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  84%|████████████████████▏   | 252/300 [02:00<00:23,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  84%|████████████████████▏   | 253/300 [02:01<00:21,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  85%|████████████████████▎   | 254/300 [02:01<00:21,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  85%|████████████████████▍   | 255/300 [02:02<00:23,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  85%|████████████████████▍   | 256/300 [02:02<00:21,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  86%|████████████████████▌   | 257/300 [02:03<00:22,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  86%|████████████████████▋   | 258/300 [02:03<00:20,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  86%|████████████████████▋   | 259/300 [02:04<00:19,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  87%|████████████████████▊   | 260/300 [02:04<00:17,  2.23it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  87%|████████████████████▉   | 261/300 [02:05<00:17,  2.28it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  87%|████████████████████▉   | 262/300 [02:05<00:17,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  88%|█████████████████████   | 263/300 [02:05<00:16,  2.27it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  88%|█████████████████████   | 264/300 [02:06<00:17,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  88%|█████████████████████▏  | 265/300 [02:07<00:18,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  89%|█████████████████████▎  | 266/300 [02:07<00:17,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  89%|█████████████████████▎  | 267/300 [02:08<00:17,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  89%|█████████████████████▍  | 268/300 [02:08<00:15,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  90%|█████████████████████▌  | 269/300 [02:09<00:15,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  90%|█████████████████████▌  | 270/300 [02:09<00:15,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  90%|█████████████████████▋  | 271/300 [02:10<00:14,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  91%|█████████████████████▊  | 272/300 [02:10<00:13,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  91%|█████████████████████▊  | 273/300 [02:10<00:12,  2.24it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  91%|█████████████████████▉  | 274/300 [02:11<00:11,  2.30it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  92%|██████████████████████  | 275/300 [02:11<00:10,  2.35it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  92%|██████████████████████  | 276/300 [02:12<00:10,  2.24it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  92%|██████████████████████▏ | 277/300 [02:12<00:11,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  93%|██████████████████████▏ | 278/300 [02:13<00:10,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  93%|██████████████████████▎ | 279/300 [02:13<00:09,  2.24it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  93%|██████████████████████▍ | 280/300 [02:14<00:09,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  94%|██████████████████████▍ | 281/300 [02:14<00:09,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  94%|██████████████████████▌ | 282/300 [02:15<00:09,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  94%|██████████████████████▋ | 283/300 [02:15<00:08,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  95%|██████████████████████▋ | 284/300 [02:16<00:07,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  95%|██████████████████████▊ | 285/300 [02:16<00:06,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  95%|██████████████████████▉ | 286/300 [02:16<00:06,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  96%|██████████████████████▉ | 287/300 [02:17<00:06,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  96%|███████████████████████ | 288/300 [02:17<00:05,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  96%|███████████████████████ | 289/300 [02:18<00:05,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  97%|███████████████████████▏| 290/300 [02:18<00:04,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  97%|███████████████████████▎| 291/300 [02:19<00:04,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  97%|███████████████████████▎| 292/300 [02:19<00:03,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  98%|███████████████████████▍| 293/300 [02:20<00:03,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  98%|███████████████████████▌| 294/300 [02:20<00:02,  2.28it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  98%|███████████████████████▌| 295/300 [02:21<00:02,  2.31it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  99%|███████████████████████▋| 296/300 [02:21<00:01,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  99%|███████████████████████▊| 297/300 [02:22<00:01,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1:  99%|███████████████████████▊| 298/300 [02:22<00:00,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1: 100%|███████████████████████▉| 299/300 [02:23<00:00,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength -0.1: 100%|████████████████████████| 300/300 [02:23<00:00,  2.15it/s]
Steering Strength:  60%|█████████████▊         | 3/5 [07:26<04:54, 147.48s/it]
Strength 0:   0%|                                     | 0/300 [00:00<?, ?it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   0%|                             | 1/300 [00:00<02:26,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   1%|▏                            | 2/300 [00:00<02:26,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   1%|▎                            | 3/300 [00:01<02:25,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   1%|▍                            | 4/300 [00:01<02:25,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   2%|▍                            | 5/300 [00:02<02:33,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   2%|▌                            | 6/300 [00:02<02:22,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   2%|▋                            | 7/300 [00:03<02:22,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   3%|▊                            | 8/300 [00:03<02:15,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   3%|▊                            | 9/300 [00:04<02:18,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   3%|▉                           | 10/300 [00:04<02:19,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   4%|█                           | 11/300 [00:05<02:28,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   4%|█                           | 12/300 [00:05<02:18,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   4%|█▏                          | 13/300 [00:06<02:12,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   5%|█▎                          | 14/300 [00:06<02:07,  2.24it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   5%|█▍                          | 15/300 [00:07<02:04,  2.29it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   5%|█▍                          | 16/300 [00:07<02:02,  2.32it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   6%|█▌                          | 17/300 [00:07<02:00,  2.36it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   6%|█▋                          | 18/300 [00:08<01:59,  2.36it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   6%|█▊                          | 19/300 [00:08<01:58,  2.38it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   7%|█▊                          | 20/300 [00:09<02:03,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   7%|█▉                          | 21/300 [00:09<02:08,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   7%|██                          | 22/300 [00:10<02:10,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   8%|██▏                         | 23/300 [00:10<02:12,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   8%|██▏                         | 24/300 [00:11<02:06,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   8%|██▎                         | 25/300 [00:11<02:01,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   9%|██▍                         | 26/300 [00:12<02:19,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   9%|██▌                         | 27/300 [00:12<02:10,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:   9%|██▌                         | 28/300 [00:13<02:11,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  10%|██▋                         | 29/300 [00:13<02:05,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  10%|██▊                         | 30/300 [00:14<02:20,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  10%|██▉                         | 31/300 [00:14<02:18,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  11%|██▉                         | 32/300 [00:15<02:09,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  11%|███                         | 33/300 [00:15<02:03,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  11%|███▏                        | 34/300 [00:16<02:13,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  12%|███▎                        | 35/300 [00:16<02:12,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  12%|███▎                        | 36/300 [00:17<02:04,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  12%|███▍                        | 37/300 [00:17<01:59,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  13%|███▌                        | 38/300 [00:17<01:56,  2.24it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  13%|███▋                        | 39/300 [00:18<01:53,  2.29it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  13%|███▋                        | 40/300 [00:18<01:51,  2.34it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  14%|███▊                        | 41/300 [00:19<01:49,  2.37it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  14%|███▉                        | 42/300 [00:19<02:01,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  14%|████                        | 43/300 [00:20<02:08,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  15%|████                        | 44/300 [00:20<02:27,  1.74it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  15%|████▏                       | 45/300 [00:21<02:14,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  15%|████▎                       | 46/300 [00:21<02:04,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  16%|████▍                       | 47/300 [00:22<01:58,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  16%|████▍                       | 48/300 [00:22<01:53,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  16%|████▌                       | 49/300 [00:23<01:51,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  17%|████▋                       | 50/300 [00:23<01:49,  2.29it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  17%|████▊                       | 51/300 [00:23<01:47,  2.31it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  17%|████▊                       | 52/300 [00:24<01:45,  2.35it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  18%|████▉                       | 53/300 [00:24<01:56,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  18%|█████                       | 54/300 [00:25<01:57,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  18%|█████▏                      | 55/300 [00:25<01:52,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  19%|█████▏                      | 56/300 [00:26<01:48,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  19%|█████▎                      | 57/300 [00:26<01:58,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  19%|█████▍                      | 58/300 [00:27<02:05,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  20%|█████▌                      | 59/300 [00:27<02:03,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  20%|█████▌                      | 60/300 [00:28<01:56,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  20%|█████▋                      | 61/300 [00:28<01:56,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  21%|█████▊                      | 62/300 [00:29<01:51,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  21%|█████▉                      | 63/300 [00:29<01:44,  2.27it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  21%|█████▉                      | 64/300 [00:30<01:41,  2.32it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  22%|██████                      | 65/300 [00:30<01:39,  2.35it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  22%|██████▏                     | 66/300 [00:31<01:50,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  22%|██████▎                     | 67/300 [00:31<01:45,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  23%|██████▎                     | 68/300 [00:31<01:42,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  23%|██████▍                     | 69/300 [00:32<01:51,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  23%|██████▌                     | 70/300 [00:32<01:46,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  24%|██████▋                     | 71/300 [00:33<01:54,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  24%|██████▋                     | 72/300 [00:33<01:58,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  24%|██████▊                     | 73/300 [00:34<01:50,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  25%|██████▉                     | 74/300 [00:34<01:45,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  25%|███████                     | 75/300 [00:35<01:41,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  25%|███████                     | 76/300 [00:35<01:38,  2.28it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  26%|███████▏                    | 77/300 [00:36<01:47,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  26%|███████▎                    | 78/300 [00:36<01:48,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  26%|███████▎                    | 79/300 [00:37<01:48,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  27%|███████▍                    | 80/300 [00:37<01:42,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  27%|███████▌                    | 81/300 [00:38<01:38,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  27%|███████▋                    | 82/300 [00:38<01:36,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  28%|███████▋                    | 83/300 [00:38<01:34,  2.31it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  28%|███████▊                    | 84/300 [00:39<01:32,  2.34it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  28%|███████▉                    | 85/300 [00:39<01:31,  2.36it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  29%|████████                    | 86/300 [00:40<01:29,  2.38it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  29%|████████                    | 87/300 [00:40<01:34,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  29%|████████▏                   | 88/300 [00:41<01:31,  2.31it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  30%|████████▎                   | 89/300 [00:41<01:36,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  30%|████████▍                   | 90/300 [00:41<01:32,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  30%|████████▍                   | 91/300 [00:42<01:30,  2.31it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  31%|████████▌                   | 92/300 [00:42<01:28,  2.34it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  31%|████████▋                   | 93/300 [00:43<01:27,  2.37it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  31%|████████▊                   | 94/300 [00:43<01:26,  2.38it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  32%|████████▊                   | 95/300 [00:44<01:25,  2.40it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  32%|████████▉                   | 96/300 [00:44<01:39,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  32%|█████████                   | 97/300 [00:45<01:35,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  33%|█████████▏                  | 98/300 [00:45<01:41,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  33%|█████████▏                  | 99/300 [00:46<01:40,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  33%|█████████                  | 100/300 [00:46<01:34,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  34%|█████████                  | 101/300 [00:46<01:31,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  34%|█████████▏                 | 102/300 [00:47<01:28,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  34%|█████████▎                 | 103/300 [00:47<01:30,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  35%|█████████▎                 | 104/300 [00:48<01:32,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  35%|█████████▍                 | 105/300 [00:48<01:38,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  35%|█████████▌                 | 106/300 [00:49<01:37,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  36%|█████████▋                 | 107/300 [00:49<01:31,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  36%|█████████▋                 | 108/300 [00:50<01:32,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  36%|█████████▊                 | 109/300 [00:50<01:32,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  37%|█████████▉                 | 110/300 [00:51<01:32,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  37%|█████████▉                 | 111/300 [00:51<01:32,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  37%|██████████                 | 112/300 [00:52<01:41,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  38%|██████████▏                | 113/300 [00:53<01:38,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  38%|██████████▎                | 114/300 [00:53<01:45,  1.76it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  38%|██████████▎                | 115/300 [00:54<01:36,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  39%|██████████▍                | 116/300 [00:54<01:29,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  39%|██████████▌                | 117/300 [00:54<01:25,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  39%|██████████▌                | 118/300 [00:55<01:30,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  40%|██████████▋                | 119/300 [00:55<01:25,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  40%|██████████▊                | 120/300 [00:56<01:21,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  40%|██████████▉                | 121/300 [00:56<01:19,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  41%|██████████▉                | 122/300 [00:57<01:17,  2.31it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  41%|███████████                | 123/300 [00:57<01:15,  2.34it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  41%|███████████▏               | 124/300 [00:57<01:14,  2.37it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  42%|███████████▎               | 125/300 [00:58<01:13,  2.38it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  42%|███████████▎               | 126/300 [00:58<01:16,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  42%|███████████▍               | 127/300 [00:59<01:14,  2.31it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  43%|███████████▌               | 128/300 [00:59<01:21,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  43%|███████████▌               | 129/300 [01:00<01:22,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  43%|███████████▋               | 130/300 [01:00<01:18,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  44%|███████████▊               | 131/300 [01:01<01:15,  2.24it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  44%|███████████▉               | 132/300 [01:01<01:13,  2.29it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  44%|███████████▉               | 133/300 [01:02<01:12,  2.31it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  45%|████████████               | 134/300 [01:02<01:14,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  45%|████████████▏              | 135/300 [01:03<01:16,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  45%|████████████▏              | 136/300 [01:03<01:13,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  46%|████████████▎              | 137/300 [01:03<01:11,  2.28it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  46%|████████████▍              | 138/300 [01:04<01:13,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  46%|████████████▌              | 139/300 [01:04<01:15,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  47%|████████████▌              | 140/300 [01:05<01:14,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  47%|████████████▋              | 141/300 [01:05<01:15,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  47%|████████████▊              | 142/300 [01:06<01:12,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  48%|████████████▊              | 143/300 [01:06<01:09,  2.24it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  48%|████████████▉              | 144/300 [01:07<01:20,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  48%|█████████████              | 145/300 [01:07<01:14,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  49%|█████████████▏             | 146/300 [01:08<01:14,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  49%|█████████████▏             | 147/300 [01:08<01:18,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  49%|█████████████▎             | 148/300 [01:09<01:17,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  50%|█████████████▍             | 149/300 [01:09<01:20,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  50%|█████████████▌             | 150/300 [01:10<01:17,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  50%|█████████████▌             | 151/300 [01:10<01:12,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  51%|█████████████▋             | 152/300 [01:11<01:09,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  51%|█████████████▊             | 153/300 [01:11<01:04,  2.27it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  51%|█████████████▊             | 154/300 [01:12<01:10,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  52%|█████████████▉             | 155/300 [01:12<01:17,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  52%|██████████████             | 156/300 [01:13<01:11,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  52%|██████████████▏            | 157/300 [01:13<01:07,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  53%|██████████████▏            | 158/300 [01:14<01:08,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  53%|██████████████▎            | 159/300 [01:14<01:04,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  53%|██████████████▍            | 160/300 [01:14<01:02,  2.24it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  54%|██████████████▍            | 161/300 [01:15<01:00,  2.29it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  54%|██████████████▌            | 162/300 [01:15<01:06,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  54%|██████████████▋            | 163/300 [01:16<01:03,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  55%|██████████████▊            | 164/300 [01:16<01:04,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  55%|██████████████▊            | 165/300 [01:17<01:04,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  55%|██████████████▉            | 166/300 [01:17<01:01,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  56%|███████████████            | 167/300 [01:18<01:00,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  56%|███████████████            | 168/300 [01:18<01:01,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  56%|███████████████▏           | 169/300 [01:19<00:59,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  57%|███████████████▎           | 170/300 [01:19<01:04,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  57%|███████████████▍           | 171/300 [01:20<01:00,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  57%|███████████████▍           | 172/300 [01:20<01:01,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  58%|███████████████▌           | 173/300 [01:21<00:58,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  58%|███████████████▋           | 174/300 [01:21<00:56,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  58%|███████████████▊           | 175/300 [01:21<00:54,  2.30it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  59%|███████████████▊           | 176/300 [01:22<01:02,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  59%|███████████████▉           | 177/300 [01:22<00:58,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  59%|████████████████           | 178/300 [01:23<00:58,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  60%|████████████████           | 179/300 [01:23<00:55,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  60%|████████████████▏          | 180/300 [01:24<00:54,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  60%|████████████████▎          | 181/300 [01:24<00:50,  2.34it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  61%|████████████████▍          | 182/300 [01:25<00:50,  2.34it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  61%|████████████████▍          | 183/300 [01:25<00:55,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  61%|████████████████▌          | 184/300 [01:26<00:52,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  62%|████████████████▋          | 185/300 [01:26<00:50,  2.27it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  62%|████████████████▋          | 186/300 [01:27<00:55,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  62%|████████████████▊          | 187/300 [01:27<00:52,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  63%|████████████████▉          | 188/300 [01:28<00:55,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  63%|█████████████████          | 189/300 [01:28<00:52,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  63%|█████████████████          | 190/300 [01:29<00:55,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  64%|█████████████████▏         | 191/300 [01:29<00:52,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  64%|█████████████████▎         | 192/300 [01:29<00:49,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  64%|█████████████████▎         | 193/300 [01:30<00:47,  2.24it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  65%|█████████████████▍         | 194/300 [01:30<00:46,  2.29it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  65%|█████████████████▌         | 195/300 [01:31<00:51,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  65%|█████████████████▋         | 196/300 [01:31<00:56,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  66%|█████████████████▋         | 197/300 [01:32<00:51,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  66%|█████████████████▊         | 198/300 [01:32<00:53,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  66%|█████████████████▉         | 199/300 [01:33<00:57,  1.77it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  67%|██████████████████         | 200/300 [01:34<00:51,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  67%|██████████████████         | 201/300 [01:34<00:57,  1.73it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  67%|██████████████████▏        | 202/300 [01:35<00:59,  1.66it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  68%|██████████████████▎        | 203/300 [01:35<00:55,  1.75it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  68%|██████████████████▎        | 204/300 [01:36<00:50,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  68%|██████████████████▍        | 205/300 [01:36<00:46,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  69%|██████████████████▌        | 206/300 [01:37<00:43,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  69%|██████████████████▋        | 207/300 [01:37<00:41,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  69%|██████████████████▋        | 208/300 [01:38<00:44,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  70%|██████████████████▊        | 209/300 [01:38<00:44,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  70%|██████████████████▉        | 210/300 [01:39<00:42,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  70%|██████████████████▉        | 211/300 [01:39<00:40,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  71%|███████████████████        | 212/300 [01:39<00:41,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  71%|███████████████████▏       | 213/300 [01:40<00:43,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  71%|███████████████████▎       | 214/300 [01:41<00:45,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  72%|███████████████████▎       | 215/300 [01:41<00:45,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  72%|███████████████████▍       | 216/300 [01:42<00:42,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  72%|███████████████████▌       | 217/300 [01:42<00:41,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  73%|███████████████████▌       | 218/300 [01:43<00:38,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  73%|███████████████████▋       | 219/300 [01:43<00:37,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  73%|███████████████████▊       | 220/300 [01:44<00:39,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  74%|███████████████████▉       | 221/300 [01:44<00:43,  1.84it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  74%|███████████████████▉       | 222/300 [01:45<00:43,  1.79it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  74%|████████████████████       | 223/300 [01:45<00:39,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  75%|████████████████████▏      | 224/300 [01:46<00:38,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  75%|████████████████████▎      | 225/300 [01:46<00:36,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  75%|████████████████████▎      | 226/300 [01:47<00:35,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  76%|████████████████████▍      | 227/300 [01:47<00:37,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  76%|████████████████████▌      | 228/300 [01:48<00:36,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  76%|████████████████████▌      | 229/300 [01:48<00:34,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  77%|████████████████████▋      | 230/300 [01:48<00:32,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  77%|████████████████████▊      | 231/300 [01:49<00:30,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  77%|████████████████████▉      | 232/300 [01:49<00:33,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  78%|████████████████████▉      | 233/300 [01:50<00:31,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  78%|█████████████████████      | 234/300 [01:50<00:29,  2.22it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  78%|█████████████████████▏     | 235/300 [01:51<00:31,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  79%|█████████████████████▏     | 236/300 [01:51<00:29,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  79%|█████████████████████▎     | 237/300 [01:52<00:28,  2.23it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  79%|█████████████████████▍     | 238/300 [01:52<00:27,  2.28it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  80%|█████████████████████▌     | 239/300 [01:53<00:30,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  80%|█████████████████████▌     | 240/300 [01:53<00:31,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  80%|█████████████████████▋     | 241/300 [01:54<00:33,  1.75it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  81%|█████████████████████▊     | 242/300 [01:54<00:30,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  81%|█████████████████████▊     | 243/300 [01:55<00:30,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  81%|█████████████████████▉     | 244/300 [01:55<00:27,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  82%|██████████████████████     | 245/300 [01:56<00:25,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  82%|██████████████████████▏    | 246/300 [01:56<00:27,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  82%|██████████████████████▏    | 247/300 [01:57<00:25,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  83%|██████████████████████▎    | 248/300 [01:57<00:24,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  83%|██████████████████████▍    | 249/300 [01:58<00:24,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  83%|██████████████████████▌    | 250/300 [01:58<00:23,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  84%|██████████████████████▌    | 251/300 [01:59<00:24,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  84%|██████████████████████▋    | 252/300 [01:59<00:23,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  84%|██████████████████████▊    | 253/300 [02:00<00:22,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  85%|██████████████████████▊    | 254/300 [02:00<00:22,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  85%|██████████████████████▉    | 255/300 [02:01<00:23,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  85%|███████████████████████    | 256/300 [02:01<00:21,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  86%|███████████████████████▏   | 257/300 [02:02<00:22,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  86%|███████████████████████▏   | 258/300 [02:02<00:20,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  86%|███████████████████████▎   | 259/300 [02:03<00:19,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  87%|███████████████████████▍   | 260/300 [02:03<00:18,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  87%|███████████████████████▍   | 261/300 [02:04<00:17,  2.27it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  87%|███████████████████████▌   | 262/300 [02:04<00:17,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  88%|███████████████████████▋   | 263/300 [02:04<00:16,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  88%|███████████████████████▊   | 264/300 [02:05<00:17,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  88%|███████████████████████▊   | 265/300 [02:05<00:16,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  89%|███████████████████████▉   | 266/300 [02:06<00:15,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  89%|████████████████████████   | 267/300 [02:06<00:15,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  89%|████████████████████████   | 268/300 [02:07<00:14,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  90%|████████████████████████▏  | 269/300 [02:07<00:14,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  90%|████████████████████████▎  | 270/300 [02:08<00:15,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  90%|████████████████████████▍  | 271/300 [02:08<00:13,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  91%|████████████████████████▍  | 272/300 [02:09<00:12,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  91%|████████████████████████▌  | 273/300 [02:09<00:11,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  91%|████████████████████████▋  | 274/300 [02:10<00:11,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  92%|████████████████████████▊  | 275/300 [02:10<00:11,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  92%|████████████████████████▊  | 276/300 [02:11<00:11,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  92%|████████████████████████▉  | 277/300 [02:11<00:11,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  93%|█████████████████████████  | 278/300 [02:12<00:10,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  93%|█████████████████████████  | 279/300 [02:12<00:09,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  93%|█████████████████████████▏ | 280/300 [02:12<00:09,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  94%|█████████████████████████▎ | 281/300 [02:13<00:10,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  94%|█████████████████████████▍ | 282/300 [02:14<00:09,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  94%|█████████████████████████▍ | 283/300 [02:14<00:08,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  95%|█████████████████████████▌ | 284/300 [02:14<00:07,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  95%|█████████████████████████▋ | 285/300 [02:15<00:06,  2.18it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  95%|█████████████████████████▋ | 286/300 [02:15<00:06,  2.25it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  96%|█████████████████████████▊ | 287/300 [02:16<00:06,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  96%|█████████████████████████▉ | 288/300 [02:16<00:05,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  96%|██████████████████████████ | 289/300 [02:17<00:05,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  97%|██████████████████████████ | 290/300 [02:17<00:04,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  97%|██████████████████████████▏| 291/300 [02:18<00:04,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  97%|██████████████████████████▎| 292/300 [02:18<00:03,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  98%|██████████████████████████▎| 293/300 [02:19<00:03,  2.27it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  98%|██████████████████████████▍| 294/300 [02:19<00:02,  2.30it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  98%|██████████████████████████▌| 295/300 [02:19<00:02,  2.33it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  99%|██████████████████████████▋| 296/300 [02:20<00:01,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  99%|██████████████████████████▋| 297/300 [02:20<00:01,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0:  99%|██████████████████████████▊| 298/300 [02:21<00:00,  2.26it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0: 100%|██████████████████████████▉| 299/300 [02:21<00:00,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 0: 100%|███████████████████████████| 300/300 [02:22<00:00,  2.17it/s]
Steering Strength:  80%|██████████████████▍    | 4/5 [09:48<02:25, 145.43s/it]
Strength 1:   0%|                                     | 0/300 [00:00<?, ?it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   0%|                             | 1/300 [00:00<02:34,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   1%|▏                            | 2/300 [00:01<02:31,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   1%|▎                            | 3/300 [00:01<02:29,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   1%|▍                            | 4/300 [00:02<02:28,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   2%|▍                            | 5/300 [00:02<02:27,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   2%|▌                            | 6/300 [00:03<02:27,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   2%|▋                            | 7/300 [00:03<02:34,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   3%|▊                            | 8/300 [00:04<02:39,  1.83it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   3%|▊                            | 9/300 [00:04<02:42,  1.79it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   3%|▉                           | 10/300 [00:05<02:36,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   4%|█                           | 11/300 [00:05<02:32,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   4%|█                           | 12/300 [00:06<02:35,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   4%|█▏                          | 13/300 [00:06<02:38,  1.81it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   5%|█▎                          | 14/300 [00:07<02:25,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   5%|█▍                          | 15/300 [00:07<02:17,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   5%|█▍                          | 16/300 [00:08<02:11,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   6%|█▌                          | 17/300 [00:08<02:13,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   6%|█▋                          | 18/300 [00:09<02:15,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   6%|█▊                          | 19/300 [00:09<02:16,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   7%|█▊                          | 20/300 [00:10<02:16,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   7%|█▉                          | 21/300 [00:10<02:24,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   7%|██                          | 22/300 [00:11<02:28,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   8%|██▏                         | 23/300 [00:11<02:24,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   8%|██▏                         | 24/300 [00:12<02:21,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   8%|██▎                         | 25/300 [00:12<02:12,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   9%|██▍                         | 26/300 [00:13<02:13,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   9%|██▌                         | 27/300 [00:13<02:13,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:   9%|██▌                         | 28/300 [00:14<02:13,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  10%|██▋                         | 29/300 [00:14<02:13,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  10%|██▊                         | 30/300 [00:15<02:13,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  10%|██▉                         | 31/300 [00:15<02:13,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  11%|██▉                         | 32/300 [00:16<02:05,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  11%|███                         | 33/300 [00:16<02:00,  2.21it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  11%|███▏                        | 34/300 [00:17<02:11,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  12%|███▎                        | 35/300 [00:17<02:11,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  12%|███▎                        | 36/300 [00:18<02:10,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  12%|███▍                        | 37/300 [00:18<02:09,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  13%|███▌                        | 38/300 [00:19<02:17,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  13%|███▋                        | 39/300 [00:19<02:14,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  13%|███▋                        | 40/300 [00:20<02:12,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  14%|███▊                        | 41/300 [00:20<02:04,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  14%|███▉                        | 42/300 [00:21<02:04,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  14%|████                        | 43/300 [00:21<02:05,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  15%|████                        | 44/300 [00:22<02:12,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  15%|████▏                       | 45/300 [00:22<02:09,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  15%|████▎                       | 46/300 [00:23<02:08,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  16%|████▍                       | 47/300 [00:23<02:00,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  16%|████▍                       | 48/300 [00:24<02:01,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  16%|████▌                       | 49/300 [00:24<01:56,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  17%|████▋                       | 50/300 [00:25<02:05,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  17%|████▊                       | 51/300 [00:25<02:11,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  17%|████▊                       | 52/300 [00:26<02:08,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  18%|████▉                       | 53/300 [00:26<02:06,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  18%|█████                       | 54/300 [00:27<02:10,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  18%|█████▏                      | 55/300 [00:27<02:07,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  19%|█████▏                      | 56/300 [00:28<02:04,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  19%|█████▎                      | 57/300 [00:28<02:04,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  19%|█████▍                      | 58/300 [00:29<02:09,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  20%|█████▌                      | 59/300 [00:29<02:12,  1.82it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  20%|█████▌                      | 60/300 [00:30<02:02,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  20%|█████▋                      | 61/300 [00:30<02:06,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  21%|█████▊                      | 62/300 [00:31<02:04,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  21%|█████▉                      | 63/300 [00:31<01:59,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  21%|█████▉                      | 64/300 [00:32<01:58,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  22%|██████                      | 65/300 [00:32<01:57,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  22%|██████▏                     | 66/300 [00:33<01:56,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  22%|██████▎                     | 67/300 [00:33<01:55,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  23%|██████▎                     | 68/300 [00:34<01:55,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  23%|██████▍                     | 69/300 [00:34<01:54,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  23%|██████▌                     | 70/300 [00:35<01:49,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  24%|██████▋                     | 71/300 [00:35<01:50,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  24%|██████▋                     | 72/300 [00:36<01:50,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  24%|██████▊                     | 73/300 [00:36<01:56,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  25%|██████▉                     | 74/300 [00:37<01:49,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  25%|███████                     | 75/300 [00:37<01:49,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  25%|███████                     | 76/300 [00:38<01:44,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  26%|███████▏                    | 77/300 [00:38<01:46,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  26%|███████▎                    | 78/300 [00:39<01:52,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  26%|███████▎                    | 79/300 [00:39<01:56,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  27%|███████▍                    | 80/300 [00:40<01:53,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  27%|███████▌                    | 81/300 [00:40<01:46,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  27%|███████▋                    | 82/300 [00:41<01:42,  2.14it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  28%|███████▋                    | 83/300 [00:41<01:43,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  28%|███████▊                    | 84/300 [00:42<01:38,  2.19it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  28%|███████▉                    | 85/300 [00:42<01:40,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  29%|████████                    | 86/300 [00:43<01:41,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  29%|████████                    | 87/300 [00:43<01:47,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  29%|████████▏                   | 88/300 [00:43<01:41,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  30%|████████▎                   | 89/300 [00:44<01:42,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  30%|████████▍                   | 90/300 [00:44<01:42,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  30%|████████▍                   | 91/300 [00:45<01:37,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  31%|████████▌                   | 92/300 [00:45<01:38,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  31%|████████▋                   | 93/300 [00:46<01:44,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  31%|████████▊                   | 94/300 [00:46<01:38,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  32%|████████▊                   | 95/300 [00:47<01:38,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  32%|████████▉                   | 96/300 [00:47<01:44,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  32%|█████████                   | 97/300 [00:48<01:38,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  33%|█████████▏                  | 98/300 [00:48<01:38,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  33%|█████████▏                  | 99/300 [00:49<01:43,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  33%|█████████                  | 100/300 [00:50<01:46,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  34%|█████████                  | 101/300 [00:50<01:49,  1.82it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  34%|█████████▏                 | 102/300 [00:51<01:45,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  34%|█████████▎                 | 103/300 [00:51<01:47,  1.83it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  35%|█████████▎                 | 104/300 [00:52<01:44,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  35%|█████████▍                 | 105/300 [00:52<01:46,  1.83it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  35%|█████████▌                 | 106/300 [00:53<01:42,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  36%|█████████▋                 | 107/300 [00:53<01:40,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  36%|█████████▋                 | 108/300 [00:54<01:43,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  36%|█████████▊                 | 109/300 [00:54<01:40,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  37%|█████████▉                 | 110/300 [00:55<01:42,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  37%|█████████▉                 | 111/300 [00:55<01:44,  1.81it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  37%|██████████                 | 112/300 [00:56<01:45,  1.78it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  38%|██████████▏                | 113/300 [00:57<01:41,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  38%|██████████▎                | 114/300 [00:57<01:37,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  38%|██████████▎                | 115/300 [00:57<01:31,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  39%|██████████▍                | 116/300 [00:58<01:30,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  39%|██████████▌                | 117/300 [00:58<01:30,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  39%|██████████▌                | 118/300 [00:59<01:29,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  40%|██████████▋                | 119/300 [00:59<01:25,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  40%|██████████▊                | 120/300 [01:00<01:26,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  40%|██████████▉                | 121/300 [01:00<01:31,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  41%|██████████▉                | 122/300 [01:01<01:29,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  41%|███████████                | 123/300 [01:01<01:24,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  41%|███████████▏               | 124/300 [01:02<01:29,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  42%|███████████▎               | 125/300 [01:02<01:23,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  42%|███████████▎               | 126/300 [01:03<01:24,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  42%|███████████▍               | 127/300 [01:03<01:24,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  43%|███████████▌               | 128/300 [01:04<01:24,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  43%|███████████▌               | 129/300 [01:04<01:19,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  43%|███████████▋               | 130/300 [01:05<01:20,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  44%|███████████▊               | 131/300 [01:05<01:16,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  44%|███████████▉               | 132/300 [01:06<01:22,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  44%|███████████▉               | 133/300 [01:06<01:22,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  45%|████████████               | 134/300 [01:07<01:22,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  45%|████████████▏              | 135/300 [01:07<01:21,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  45%|████████████▏              | 136/300 [01:08<01:17,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  46%|████████████▎              | 137/300 [01:08<01:14,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  46%|████████████▍              | 138/300 [01:09<01:19,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  46%|████████████▌              | 139/300 [01:09<01:19,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  47%|████████████▌              | 140/300 [01:10<01:17,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  47%|████████████▋              | 141/300 [01:10<01:13,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  47%|████████████▊              | 142/300 [01:11<01:19,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  48%|████████████▊              | 143/300 [01:11<01:18,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  48%|████████████▉              | 144/300 [01:12<01:18,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  48%|█████████████              | 145/300 [01:12<01:13,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  49%|█████████████▏             | 146/300 [01:13<01:14,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  49%|█████████████▏             | 147/300 [01:13<01:14,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  49%|█████████████▎             | 148/300 [01:14<01:14,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  50%|█████████████▍             | 149/300 [01:14<01:14,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  50%|█████████████▌             | 150/300 [01:14<01:13,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  50%|█████████████▌             | 151/300 [01:15<01:13,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  51%|█████████████▋             | 152/300 [01:16<01:13,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  51%|█████████████▊             | 153/300 [01:16<01:07,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  51%|█████████████▊             | 154/300 [01:16<01:08,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  52%|█████████████▉             | 155/300 [01:17<01:09,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  52%|██████████████             | 156/300 [01:17<01:09,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  52%|██████████████▏            | 157/300 [01:18<01:09,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  53%|██████████████▏            | 158/300 [01:18<01:09,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  53%|██████████████▎            | 159/300 [01:19<01:09,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  53%|██████████████▍            | 160/300 [01:19<01:12,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  54%|██████████████▍            | 161/300 [01:20<01:11,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  54%|██████████████▌            | 162/300 [01:20<01:10,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  54%|██████████████▋            | 163/300 [01:21<01:06,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  55%|██████████████▊            | 164/300 [01:21<01:09,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  55%|██████████████▊            | 165/300 [01:22<01:11,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  55%|██████████████▉            | 166/300 [01:23<01:09,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  56%|███████████████            | 167/300 [01:23<01:05,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  56%|███████████████            | 168/300 [01:23<01:04,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  56%|███████████████▏           | 169/300 [01:24<01:01,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  57%|███████████████▎           | 170/300 [01:24<01:02,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  57%|███████████████▍           | 171/300 [01:25<00:59,  2.16it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  57%|███████████████▍           | 172/300 [01:25<01:01,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  58%|███████████████▌           | 173/300 [01:26<01:04,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  58%|███████████████▋           | 174/300 [01:26<01:06,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  58%|███████████████▊           | 175/300 [01:27<01:05,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  59%|███████████████▊           | 176/300 [01:27<01:03,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  59%|███████████████▉           | 177/300 [01:28<01:02,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  59%|████████████████           | 178/300 [01:28<01:01,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  60%|████████████████           | 179/300 [01:29<01:03,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  60%|████████████████▏          | 180/300 [01:30<01:05,  1.83it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  60%|████████████████▎          | 181/300 [01:30<00:58,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  61%|████████████████▍          | 182/300 [01:30<00:58,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  61%|████████████████▍          | 183/300 [01:31<01:00,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  61%|████████████████▌          | 184/300 [01:32<00:59,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  62%|████████████████▋          | 185/300 [01:32<01:01,  1.88it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  62%|████████████████▋          | 186/300 [01:33<01:02,  1.82it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  62%|████████████████▊          | 187/300 [01:33<01:03,  1.79it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  63%|████████████████▉          | 188/300 [01:34<01:03,  1.77it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  63%|█████████████████          | 189/300 [01:34<01:03,  1.76it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  63%|█████████████████          | 190/300 [01:35<01:00,  1.83it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  64%|█████████████████▏         | 191/300 [01:35<00:58,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  64%|█████████████████▎         | 192/300 [01:36<00:53,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  64%|█████████████████▎         | 193/300 [01:36<00:53,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  65%|█████████████████▍         | 194/300 [01:37<00:55,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  65%|█████████████████▌         | 195/300 [01:38<00:56,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  65%|█████████████████▋         | 196/300 [01:38<00:54,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  66%|█████████████████▋         | 197/300 [01:39<00:53,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  66%|█████████████████▊         | 198/300 [01:39<00:52,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  66%|█████████████████▉         | 199/300 [01:40<00:53,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  67%|██████████████████         | 200/300 [01:40<00:49,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  67%|██████████████████         | 201/300 [01:41<00:52,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  67%|██████████████████▏        | 202/300 [01:41<00:51,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  68%|██████████████████▎        | 203/300 [01:42<00:50,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  68%|██████████████████▎        | 204/300 [01:42<00:48,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  68%|██████████████████▍        | 205/300 [01:43<00:50,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  69%|██████████████████▌        | 206/300 [01:43<00:48,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  69%|██████████████████▋        | 207/300 [01:44<00:47,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  69%|██████████████████▋        | 208/300 [01:44<00:48,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  70%|██████████████████▊        | 209/300 [01:45<00:47,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  70%|██████████████████▉        | 210/300 [01:45<00:43,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  70%|██████████████████▉        | 211/300 [01:46<00:41,  2.15it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  71%|███████████████████        | 212/300 [01:46<00:42,  2.09it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  71%|███████████████████▏       | 213/300 [01:47<00:42,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  71%|███████████████████▎       | 214/300 [01:47<00:41,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  72%|███████████████████▎       | 215/300 [01:48<00:43,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  72%|███████████████████▍       | 216/300 [01:48<00:42,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  72%|███████████████████▌       | 217/300 [01:49<00:41,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  73%|███████████████████▌       | 218/300 [01:49<00:41,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  73%|███████████████████▋       | 219/300 [01:50<00:41,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  73%|███████████████████▊       | 220/300 [01:50<00:40,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  74%|███████████████████▉       | 221/300 [01:51<00:41,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  74%|███████████████████▉       | 222/300 [01:51<00:40,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  74%|████████████████████       | 223/300 [01:52<00:39,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  75%|████████████████████▏      | 224/300 [01:52<00:38,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  75%|████████████████████▎      | 225/300 [01:53<00:39,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  75%|████████████████████▎      | 226/300 [01:53<00:38,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  76%|████████████████████▍      | 227/300 [01:54<00:37,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  76%|████████████████████▌      | 228/300 [01:54<00:36,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  76%|████████████████████▌      | 229/300 [01:55<00:35,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  77%|████████████████████▋      | 230/300 [01:55<00:36,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  77%|████████████████████▊      | 231/300 [01:56<00:35,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  77%|████████████████████▉      | 232/300 [01:56<00:36,  1.86it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  78%|████████████████████▉      | 233/300 [01:57<00:35,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  78%|█████████████████████      | 234/300 [01:58<00:35,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  78%|█████████████████████▏     | 235/300 [01:58<00:34,  1.89it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  79%|█████████████████████▏     | 236/300 [01:59<00:33,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  79%|█████████████████████▎     | 237/300 [01:59<00:32,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  79%|█████████████████████▍     | 238/300 [02:00<00:31,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  80%|█████████████████████▌     | 239/300 [02:00<00:32,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  80%|█████████████████████▌     | 240/300 [02:01<00:31,  1.91it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  80%|█████████████████████▋     | 241/300 [02:01<00:31,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  81%|█████████████████████▊     | 242/300 [02:02<00:30,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  81%|█████████████████████▊     | 243/300 [02:02<00:28,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  81%|█████████████████████▉     | 244/300 [02:03<00:28,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  82%|██████████████████████     | 245/300 [02:03<00:27,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  82%|██████████████████████▏    | 246/300 [02:04<00:26,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  82%|██████████████████████▏    | 247/300 [02:04<00:26,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  83%|██████████████████████▎    | 248/300 [02:05<00:25,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  83%|██████████████████████▍    | 249/300 [02:05<00:25,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  83%|██████████████████████▌    | 250/300 [02:06<00:24,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  84%|██████████████████████▌    | 251/300 [02:06<00:24,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  84%|██████████████████████▋    | 252/300 [02:07<00:24,  1.92it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  84%|██████████████████████▊    | 253/300 [02:07<00:22,  2.05it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  85%|██████████████████████▊    | 254/300 [02:08<00:23,  1.94it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  85%|██████████████████████▉    | 255/300 [02:08<00:22,  1.96it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  85%|███████████████████████    | 256/300 [02:09<00:21,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  86%|███████████████████████▏   | 257/300 [02:09<00:20,  2.06it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  86%|███████████████████████▏   | 258/300 [02:10<00:21,  1.95it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  86%|███████████████████████▎   | 259/300 [02:10<00:20,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  87%|███████████████████████▍   | 260/300 [02:11<00:19,  2.08it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  87%|███████████████████████▍   | 261/300 [02:11<00:17,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  87%|███████████████████████▌   | 262/300 [02:12<00:18,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  88%|███████████████████████▋   | 263/300 [02:12<00:18,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  88%|███████████████████████▊   | 264/300 [02:13<00:17,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  88%|███████████████████████▊   | 265/300 [02:13<00:17,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  89%|███████████████████████▉   | 266/300 [02:14<00:16,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  89%|████████████████████████   | 267/300 [02:14<00:16,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  89%|████████████████████████   | 268/300 [02:14<00:15,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  90%|████████████████████████▏  | 269/300 [02:15<00:14,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  90%|████████████████████████▎  | 270/300 [02:15<00:14,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  90%|████████████████████████▍  | 271/300 [02:16<00:13,  2.17it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  91%|████████████████████████▍  | 272/300 [02:16<00:13,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  91%|████████████████████████▌  | 273/300 [02:17<00:12,  2.12it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  91%|████████████████████████▋  | 274/300 [02:17<00:13,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  92%|████████████████████████▊  | 275/300 [02:18<00:11,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  92%|████████████████████████▊  | 276/300 [02:18<00:12,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  92%|████████████████████████▉  | 277/300 [02:19<00:11,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  93%|█████████████████████████  | 278/300 [02:19<00:10,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  93%|█████████████████████████  | 279/300 [02:20<00:10,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  93%|█████████████████████████▏ | 280/300 [02:20<00:09,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  94%|█████████████████████████▎ | 281/300 [02:21<00:09,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  94%|█████████████████████████▍ | 282/300 [02:21<00:08,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  94%|█████████████████████████▍ | 283/300 [02:22<00:08,  2.11it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  95%|█████████████████████████▌ | 284/300 [02:22<00:07,  2.20it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  95%|█████████████████████████▋ | 285/300 [02:23<00:07,  2.03it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  95%|█████████████████████████▋ | 286/300 [02:23<00:06,  2.13it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  96%|█████████████████████████▊ | 287/300 [02:24<00:06,  1.99it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  96%|█████████████████████████▉ | 288/300 [02:24<00:06,  1.90it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  96%|██████████████████████████ | 289/300 [02:25<00:05,  1.85it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  97%|██████████████████████████ | 290/300 [02:25<00:05,  1.97it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  97%|██████████████████████████▏| 291/300 [02:26<00:04,  1.98it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  97%|██████████████████████████▎| 292/300 [02:26<00:03,  2.10it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  98%|██████████████████████████▎| 293/300 [02:27<00:03,  2.07it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  98%|██████████████████████████▍| 294/300 [02:27<00:02,  2.04it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  98%|██████████████████████████▌| 295/300 [02:28<00:02,  1.93it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  99%|██████████████████████████▋| 296/300 [02:28<00:02,  1.87it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  99%|██████████████████████████▋| 297/300 [02:29<00:01,  2.00it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1:  99%|██████████████████████████▊| 298/300 [02:29<00:00,  2.01it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1: 100%|██████████████████████████▉| 299/300 [02:30<00:00,  2.02it/s]

(16384,)
torch.Size([16384, 3584])

  0%|          | 0/16 [00:00<?, ?it/s]

Strength 1: 100%|███████████████████████████| 300/300 [02:30<00:00,  2.12it/s]
Steering Strength: 100%|███████████████████████| 5/5 [12:19<00:00, 147.85s/it]

## Evaluation

In [31]:
results = pd.read_csv("/shared/3/projects/bangzhao/interpretability/all-emotions-test/steered_predictions_all.csv")

In [42]:
results_renamed = results.rename(columns={
    'label': 'original_prediction',
    'prediction': 'steered_prediction'
})

results_renamed = results_renamed[results_renamed['steering_strength']==0.5]
train_df_subset = train_df.iloc[:300].drop(columns=['output'])

merged_df = train_df_subset.reset_index(drop=True).join(results_renamed.reset_index(drop=True))

In [43]:
# Normalize predictions and ground truth (case insensitive)
merged_df['steered_correct'] = merged_df['steered_prediction'].str.strip().str.lower() == merged_df['label']
merged_df['original_correct'] = merged_df['original_prediction'].str.strip().str.lower() == merged_df['label']

# Calculate accuracy
steered_accuracy = merged_df['steered_correct'].mean()
original_accuracy = merged_df['original_correct'].mean()

print(f"Steered Prediction Accuracy: {steered_accuracy:.2%}")
print(f"Original Prediction Accuracy: {original_accuracy:.2%}")

Steered Prediction Accuracy: 65.33%
Original Prediction Accuracy: 70.33%

## steering

In [ ]:
# from tqdm import tqdm
# from functools import partial


# def steering(activations, hook, steering_strength=1.0, steering_vector=None):
#     return activations + steering_strength * steering_vector


# def generate_with_steering(
#     model,
#     sae,
#     prompt,
#     svd_direction,
#     steering_strength=1.0,
#     max_new_tokens=16,
# ):
#     input_ids = model.to_tokens(prompt, prepend_bos=sae.cfg.prepend_bos)
#     print(svd_direction.shape)
#     print(sae.W_dec.shape)

#     svd_direction = torch.tensor(svd_direction, device=sae.W_dec.device, dtype=sae.W_dec.dtype)
#     steering_vector = (svd_direction @ sae.W_dec).to(model.cfg.device)
#     # steering_vector = sae.W_dec[steering_feature].to(model.cfg.device)

#     steering_hook = partial(
#         steering,
#         steering_vector=steering_vector,
#         steering_strength=steering_strength
#     )

#     # standard transformerlens syntax for a hook context for generation
#     with model.hooks(fwd_hooks=[(sae.cfg.hook_name, steering_hook)]):
#         output = model.generate(
#             input_ids,
#             max_new_tokens=max_new_tokens,
#             temperature=0.001,
#             stop_at_eos=False if device == "mps" else True,
#             prepend_bos=sae.cfg.prepend_bos,
#         )

#     return model.tokenizer.decode(output[0])

In [ ]:
# index = 1831
# prompt = train_error_prompts[index].split('\nAnswer:')[0] + "\nAnswer: "
# print('Original Prediction:', train_df.iloc[index].output)
# print('Original Label:', train_df.iloc[index].label)
# # print(prompt)

# normal_text = model.generate(
#     prompt,
#     max_new_tokens=16,
#     stop_at_eos=False if device == "mps" else True,
#     prepend_bos=sae.cfg.prepend_bos,
#     do_sample=False
# )

# print("\nNormal text (without steering):")
# print(normal_text.split('Answer:')[1])

# # Generate text with steering
# steered_text = generate_with_steering(model, sae, prompt, svd_direction=delta, steering_strength=50)
# print("Steered text:")
# print(steered_text.split('Answer:')[1])

In [ ]:
# predictions = []
# for index in range(len(train_df)):
#     prompt = train_error_prompts[index].split('\nAnswer:')[0] + "\nAnswer: "
       
#     # Generate text with steering
#     steered_text = generate_with_steering(model, sae, prompt, svd_direction=delta, steering_strength=-10.0)
#     prediction = steered_text.split('\nAnswer:')[1]
#     predictions.append(prediction)

In [ ]:
# labels = [prompt.split('\nAnswer:')[1] for prompt in train_error_prompts]

In [ ]:
# labels

In [ ]:
predictions

In [ ]:
# delta

## Test features

In [ ]:
# topk_indices = np.argsort(np.abs(delta))[-20:][::-1]

# # Get their corresponding magnitudes
# topk_magnitudes = np.abs(delta[topk_indices])
# topk_features = list(zip(topk_indices, topk_magnitudes))

# for idx, mag in topk_features:
#     print(f"Feature {idx} has magnitude {mag:.4f}")

In [ ]:
# from IPython.display import IFrame


# html_template = "https://neuronpedia.org/{}/{}/{}?embed=true&embedexplanation=true&embedplots=true&embedtest=true&height=300"

# def get_dashboard_html(sae_release="gemma-2-9b-it", sae_id="20-gemmascope-res-16k", feature_idx=0):
#     return html_template.format(sae_release, sae_id, feature_idx)

# html = get_dashboard_html(
#     sae_release="gemma-2-9b-it", sae_id="20-gemmascope-res-16k", feature_idx=9374
# )
# IFrame(html, width=1200, height=600)

In [ ]:
from transformer_lens.utils import test_prompt

In [ ]:
sae.use_error_term

In [ ]:
prompt = train_error_prompts[1]

print(prompt)

_, cache = model.run_with_cache_with_saes(prompt, saes=[sae])

print([(k, v.shape) for k, v in cache.items() if "sae" in k])

In [ ]:
from IPython.display import IFrame

html_template = "https://neuronpedia.org/{}/{}/{}?embed=true&embedexplanation=true&embedplots=true&embedtest=true&height=300"

def get_dashboard_html(sae_release="gemma-2-9b-it", sae_id="20-gemmascope-res-16k", feature_idx=0):
    return html_template.format(sae_release, sae_id, feature_idx)

In [ ]:
# let's look at which features fired at layer 8 at the final token position

# hover over lines to see the Feature ID.
px.line(
    cache["blocks.20.hook_resid_post.hook_sae_acts_post"][0, -1, :].cpu().numpy(),
    title="Feature activations at the final token position",
    labels={"index": "Feature", "value": "Activation"},
).show()

# let's print the top 5 features and how much they fired
vals, inds = torch.topk(
    cache["blocks.20.hook_resid_post.hook_sae_acts_post"][0, -1, :], 5
)
for val, ind in zip(vals, inds):
    print(f"Feature {ind} fired {val:.2f}")
    html = get_dashboard_html(
        sae_release="gemma-2-9b-it", sae_id="20-gemmascope-res-16k", feature_idx=ind
    )
    display(IFrame(html, width=1200, height=300))

### The Contrast Pairs Trick

Sometimes we may be interested in which features fire differently between two prompts. Let's investigate this question by comparing the resultant activations. As we can see, using the prompt below changes the logit prediction considerably:

In [ ]:
# prompt = [
#     "Jack failed his math exam. He thought it meant he wasn't smart enough and felt deeply frustrated and discouraged.",
#     "Jack failed his math exam. He saw it as a sign to improve and felt determined to study harder and do better next time.",
# ]

prompt = [
    "Jack failed his math exam. He felt deeply discouraged, believing he was incapable of achieving anything meaningful.",
    "Jack failed his math exam. He felt motivated, viewing the experience as an opportunity to improve himself.",
]

_, cache = model.run_with_cache_with_saes(prompt, saes=[sae])
print([(k, v.shape) for k, v in cache.items() if "sae" in k])

# feature_activation_df = pd.DataFrame(
#     cache["blocks.7.hook_resid_pre.hook_sae_acts_post"][0, -1, :].cpu().numpy(),
#     index=[f"feature_{i}" for i in range(sae.cfg.d_sae)],
# )
# feature_activation_df.columns = ["heavens_and_the"]
# feature_activation_df["cat_and_the"] = (
#     cache["blocks.7.hook_resid_pre.hook_sae_acts_post"][1, -1, :].cpu().numpy()
# )
# feature_activation_df["diff"] = (
#     feature_activation_df["heavens_and_the"] - feature_activation_df["cat_and_the"]
# )

# fig = px.line(
#     feature_activation_df,
#     title="Feature activations for the prompt",
#     labels={"index": "Feature", "value": "Activation"},
# )

# # hide the x-ticks
# fig.update_xaxes(showticklabels=False)
# fig.show()

In [ ]:
cache

We can see that there are differences, but let's plot the feature dashboards for the features with the biggest diffs to see what they are. We can see that the biggest difference is that there is now an active "animal" feature.

In [ ]:
cache["blocks.31.hook_resid_post.hook_sae_acts_post"].shape

In [ ]:
# let's look at the biggest features in terms of absolute difference

diff = (
    cache["blocks.31.hook_resid_post.hook_sae_acts_post"][1, -1, :].cpu()
    - cache["blocks.31.hook_resid_post.hook_sae_acts_post"][0, -1, :].cpu()
    # cache["blocks.20.hook_resid_post.hook_sae_acts_post"][0, -1, :].cpu()
)
vals, inds = torch.topk(torch.abs(diff), 5)
for val, ind in zip(vals, inds):
    print(f"Feature {ind} had a difference of {val:.2f}")
    # html = get_dashboard_html(
    #     sae_release="gpt2-small", sae_id="7-res-jb", feature_idx=ind
    # )
    # display(IFrame(html, width=1200, height=300))

In [ ]:
from IPython.display import IFrame

# get a random feature from the SAE
# feature_idx = torch.randint(0, sae.cfg.d_sae, (1,)).item()

html_template = "https://neuronpedia.org/{}/{}/{}?embed=true&embedexplanation=true&embedplots=true&embedtest=true&height=300"


def get_dashboard_html(sae_release="gemma-2-9b", sae_id="31-gemmascope-res-16k", feature_idx=0):
    return html_template.format(sae_release, sae_id, feature_idx)

html = get_dashboard_html(
    sae_release="gemma-2-9b-it", sae_id="31-gemmascope-res-131k", feature_idx=51034
)
IFrame(html, width=1200, height=600)

In [ ]:
print(sae.cfg.dataset_path)

In [ ]:
# from datasets import load_dataset

# hf_dataset = load_dataset("allenai/c4", "en", split="train", streaming=True)

In [ ]:
# # instantiate an object to hold activations from a dataset
# from sae_lens import ActivationsStore

# # a convenient way to instantiate an activation store is to use the from_sae method
# activation_store = ActivationsStore.from_sae(
#     model=model,
#     sae=sae,
#     streaming=True,
#     dataset=hf_dataset,
#     # fairly conservative parameters here so can use same for larger
#     # models without running out of memory.
#     store_batch_size_prompts=8,
#     train_batch_size_tokens=4096,
#     n_batches_in_buffer=32,
#     device=device,
# )

## Feature Steering

In [ ]:
# from tqdm import tqdm
# from functools import partial


# def find_max_activation(model, sae, activation_store, feature_idx, num_batches=10):
#     """
#     Find the maximum activation for a given feature index. This is useful for
#     calibrating the right amount of the feature to add.
#     """
#     max_activation = 0.0

#     pbar = tqdm(range(num_batches))
#     for _ in pbar:
#         tokens = activation_store.get_batch_tokens()

#         _, cache = model.run_with_cache(
#             tokens,
#             stop_at_layer=sae.cfg.hook_layer + 1,
#             names_filter=[sae.cfg.hook_name],
#         )
#         sae_in = cache[sae.cfg.hook_name]
#         feature_acts = sae.encode(sae_in).squeeze()

#         feature_acts = feature_acts.flatten(0, 1)
#         batch_max_activation = feature_acts[:, feature_idx].max().item()
#         max_activation = max(max_activation, batch_max_activation)

#         pbar.set_description(f"Max activation: {max_activation:.4f}")

#     return max_activation


# def steering(
#     activations, hook, steering_strength=1.0, steering_vector=None, max_act=1.0
# ):
#     # Note if the feature fires anyway, we'd be adding to that here.
#     return activations + max_act * steering_strength * steering_vector


# def generate_with_steering(
#     model,
#     sae,
#     prompt,
#     steering_feature,
#     max_act,
#     steering_strength=1.0,
#     max_new_tokens=95,
# ):
#     input_ids = model.to_tokens(prompt, prepend_bos=sae.cfg.prepend_bos)

#     steering_vector = sae.W_dec[steering_feature].to(model.cfg.device)

#     steering_hook = partial(
#         steering,
#         steering_vector=steering_vector,
#         steering_strength=steering_strength,
#         max_act=max_act,
#     )

#     # standard transformerlens syntax for a hook context for generation
#     with model.hooks(fwd_hooks=[(sae.cfg.hook_name, steering_hook)]):
#         output = model.generate(
#             input_ids,
#             max_new_tokens=max_new_tokens,
#             temperature=0.7,
#             top_p=0.9,
#             stop_at_eos=False if device == "mps" else True,
#             prepend_bos=sae.cfg.prepend_bos,
#         )

#     return model.tokenizer.decode(output[0])


# # Choose a feature to steer
# steering_feature = steering_feature = 11255  # Choose a feature to steer towards

# # Find the maximum activation for this feature
# max_act = find_max_activation(model, sae, activation_store, steering_feature)
# print(f"Maximum activation for feature {steering_feature}: {max_act:.4f}")

# prompt = """Choose the most appropriate emotion from the following list: joy, sadness, anger, disgust, fear, guilt, and shame. Respond with only the emotion, without any explanation.
# Experience: New Year's Eve party in the country, I hardly knew a person; my partner spent most of the time at the bar. I had little opportunity to get to know people because our table was separated and my boyfriend's parents were present. 
# Answer:
# """

# normal_text = model.generate(
#     prompt,
#     max_new_tokens=16,
#     stop_at_eos=False if device == "mps" else True,
#     prepend_bos=sae.cfg.prepend_bos,
# )

# print("\nNormal text (without steering):")
# print(normal_text)

# # Generate text with steering
# steered_text = generate_with_steering(
#     model, sae, prompt, steering_feature, max_act, steering_strength=1.0
# )
# print("Steered text:")
# print(steered_text)

In [ ]:
# Experiment with different steering strengths
print("\nExperimenting with different steering strengths:")
for strength in [-4.0, -2.0, -1.0, 0.2, 0.5, 1.0, 2.0, 4.0]:
    steered_text = generate_with_steering(
        model, sae, prompt, steering_feature, max_act, steering_strength=strength
    )
    print(f"\nSteering strength {strength}:")
    print(steered_text)

We can also do this via the Neuronpedia AP or on the website [here](https://www.neuronpedia.org/steer/). The example below steers for just a few tokens with a feature that does something very specific. Can you work out what it's doing?

In [ ]:
import requests
import numpy as np

url = "https://www.neuronpedia.org/api/steer"

payload = {
    # "prompt": "A knight in shining",
    # "prompt": "He had to fight back in self-",
    "prompt": "In the middle of the universe is the galactic",
    # "prompt": "Oh no. We're running on empty. Its time to fill up the car with",
    # "prompt": "Sure, I'm happy to pay. I don't have any cash on me but let me write you a",
    "modelId": "gpt2-small",
    "features": [
        {"modelId": "gpt2-small", "layer": "7-res-jb", "index": 6770, "strength": 8}
    ],
    "temperature": 0.2,
    "n_tokens": 2,
    "freq_penalty": 1,
    "seed": np.random.randint(100),
    "strength_multiplier": 4,
}
headers = {"Content-Type": "application/json"}

response = requests.post(url, json=payload, headers=headers)

print(response.json())

In [ ]:
import requests
import numpy as np

url = "https://www.neuronpedia.org/api/steer"

payload = {
    "prompt": 'I wrote a letter to my girlfiend. It said "',
    "modelId": "gpt2-small",
    "features": [
        {"modelId": "gpt2-small", "layer": "7-res-jb", "index": 20115, "strength": 4}
    ],
    "temperature": 0.7,
    "n_tokens": 120,
    "freq_penalty": 1,
    "seed": np.random.randint(100),
    "strength_multiplier": 4,
}
headers = {"Content-Type": "application/json"}

response = requests.post(url, json=payload, headers=headers)

print(response.json())

## Feature Ablation

Feature ablation is also worth looking at. In a way, it's a special case of steering where the value of the feature is always zeroed out.

Here we do the following:
1. Use test prompt rather than generate to get more nuance. 
2. attach a hook to the SAE feature activations.
3. 0 out a feature at all positions (we know that the default feature fires at the final position.)
4. Check whether this ablation is more / less effective if we include the error term (info our SAE isn't capturing).

Note that the existence of [The Hydra Effect](https://arxiv.org/abs/2307.15771) can make reasoning about ablation experiments difficult.

In [ ]:
from transformer_lens.utils import test_prompt
from functools import partial


def test_prompt_with_ablation(model, sae, prompt, answer, ablation_features):
    def ablate_feature_hook(feature_activations, hook, feature_ids, position=None):
        if position is None:
            feature_activations[:, :, feature_ids] = 0
        else:
            feature_activations[:, position, feature_ids] = 0

        return feature_activations

    ablation_hook = partial(ablate_feature_hook, feature_ids=ablation_features)

    model.add_sae(sae)
    hook_point = sae.cfg.hook_name + ".hook_sae_acts_post"
    model.add_hook(hook_point, ablation_hook, "fwd")

    test_prompt(prompt, answer, model)

    model.reset_hooks()
    model.reset_saes()


# Example usage in a notebook:

# Assume model and sae are already defined

# Choose a feature to ablate

model.reset_hooks(including_permanent=True)
prompt = "In the beginning, God created the heavens and the"
answer = "earth"
test_prompt(prompt, answer, model)


# Generate text with feature ablation
print("Test Prompt with feature ablation and no error term")
ablation_feature = 16873  # Replace with any feature index you're interested in. We use the religion feature
sae.use_error_term = False
test_prompt_with_ablation(model, sae, prompt, answer, ablation_feature)

print("Test Prompt with feature ablation and error term")
ablation_feature = 16873  # Replace with any feature index you're interested in. We use the religion feature
sae.use_error_term = True
test_prompt_with_ablation(model, sae, prompt, answer, ablation_feature)

# Feature Attribution

In [ ]:
from dataclasses import dataclass
from functools import partial
from typing import Any, Literal, NamedTuple, Callable

import torch
from sae_lens import SAE
from transformer_lens import HookedTransformer
from transformer_lens.hook_points import HookPoint


class SaeReconstructionCache(NamedTuple):
    sae_in: torch.Tensor
    feature_acts: torch.Tensor
    sae_out: torch.Tensor
    sae_error: torch.Tensor


def track_grad(tensor: torch.Tensor) -> None:
    """wrapper around requires_grad and retain_grad"""
    tensor.requires_grad_(True)
    tensor.retain_grad()


@dataclass
class ApplySaesAndRunOutput:
    model_output: torch.Tensor
    model_activations: dict[str, torch.Tensor]
    sae_activations: dict[str, SaeReconstructionCache]

    def zero_grad(self) -> None:
        """Helper to zero grad all tensors in this object."""
        self.model_output.grad = None
        for act in self.model_activations.values():
            act.grad = None
        for cache in self.sae_activations.values():
            cache.sae_in.grad = None
            cache.feature_acts.grad = None
            cache.sae_out.grad = None
            cache.sae_error.grad = None


def apply_saes_and_run(
    model: HookedTransformer,
    saes: dict[str, SAE],
    input: Any,
    include_error_term: bool = True,
    track_model_hooks: list[str] | None = None,
    return_type: Literal["logits", "loss"] = "logits",
    track_grads: bool = False,
) -> ApplySaesAndRunOutput:
    """
    Apply the SAEs to the model at the specific hook points, and run the model.
    By default, this will include a SAE error term which guarantees that the SAE
    will not affect model output. This function is designed to work correctly with
    backprop as well, so it can be used for gradient-based feature attribution.

    Args:
        model: the model to run
        saes: the SAEs to apply
        input: the input to the model
        include_error_term: whether to include the SAE error term to ensure the SAE doesn't affect model output. Default True
        track_model_hooks: a list of hook points to record the activations and gradients. Default None
        return_type: this is passed to the model.run_with_hooks function. Default "logits"
        track_grads: whether to track gradients. Default False
    """

    fwd_hooks = []
    bwd_hooks = []

    sae_activations: dict[str, SaeReconstructionCache] = {}
    model_activations: dict[str, torch.Tensor] = {}

    # this hook just track the SAE input, output, features, and error. If `track_grads=True`, it also ensures
    # that requires_grad is set to True and retain_grad is called for intermediate values.
    def reconstruction_hook(sae_in: torch.Tensor, hook: HookPoint, hook_point: str):  # noqa: ARG001
        sae = saes[hook_point]
        feature_acts = sae.encode(sae_in)
        sae_out = sae.decode(feature_acts)
        sae_error = (sae_in - sae_out).detach().clone()
        if track_grads:
            track_grad(sae_error)
            track_grad(sae_out)
            track_grad(feature_acts)
            track_grad(sae_in)
        sae_activations[hook_point] = SaeReconstructionCache(
            sae_in=sae_in,
            feature_acts=feature_acts,
            sae_out=sae_out,
            sae_error=sae_error,
        )

        if include_error_term:
            return sae_out + sae_error
        return sae_out

    def sae_bwd_hook(output_grads: torch.Tensor, hook: HookPoint):  # noqa: ARG001
        # this just passes the output grads to the input, so the SAE gets the same grads despite the error term hackery
        return (output_grads,)

    # this hook just records model activations, and ensures that intermediate activations have gradient tracking turned on if needed
    def tracking_hook(hook_input: torch.Tensor, hook: HookPoint, hook_point: str):  # noqa: ARG001
        model_activations[hook_point] = hook_input
        if track_grads:
            track_grad(hook_input)
        return hook_input

    for hook_point in saes.keys():
        fwd_hooks.append(
            (hook_point, partial(reconstruction_hook, hook_point=hook_point))
        )
        bwd_hooks.append((hook_point, sae_bwd_hook))
    for hook_point in track_model_hooks or []:
        fwd_hooks.append((hook_point, partial(tracking_hook, hook_point=hook_point)))

    # now, just run the model while applying the hooks
    with model.hooks(fwd_hooks=fwd_hooks, bwd_hooks=bwd_hooks):
        model_output = model(input, return_type=return_type)

    return ApplySaesAndRunOutput(
        model_output=model_output,
        model_activations=model_activations,
        sae_activations=sae_activations,
    )

In [ ]:
from dataclasses import dataclass
from transformer_lens.hook_points import HookPoint
from dataclasses import dataclass
from functools import partial
from typing import Any, Literal, NamedTuple

import torch
from sae_lens import SAE
from transformer_lens import HookedTransformer
from transformer_lens.hook_points import HookPoint

EPS = 1e-8

torch.set_grad_enabled(True)


@dataclass
class AttributionGrads:
    metric: torch.Tensor
    model_output: torch.Tensor
    model_activations: dict[str, torch.Tensor]
    sae_activations: dict[str, SaeReconstructionCache]


@dataclass
class Attribution:
    model_attributions: dict[str, torch.Tensor]
    model_activations: dict[str, torch.Tensor]
    model_grads: dict[str, torch.Tensor]
    sae_feature_attributions: dict[str, torch.Tensor]
    sae_feature_activations: dict[str, torch.Tensor]
    sae_feature_grads: dict[str, torch.Tensor]
    sae_errors_attribution_proportion: dict[str, float]


def calculate_attribution_grads(
    model: HookedSAETransformer,
    prompt: str,
    metric_fn: Callable[[torch.Tensor], torch.Tensor],
    track_hook_points: list[str] | None = None,
    include_saes: dict[str, SAE] | None = None,
    return_logits: bool = True,
    include_error_term: bool = True,
) -> AttributionGrads:
    """
    Wrapper around apply_saes_and_run that calculates gradients wrt to the metric_fn.
    Tracks grads for both SAE feature and model neurons, and returns them in a structured format.
    """
    output = apply_saes_and_run(
        model,
        saes=include_saes or {},
        input=prompt,
        return_type="logits" if return_logits else "loss",
        track_model_hooks=track_hook_points,
        include_error_term=include_error_term,
        track_grads=True,
    )
    metric = metric_fn(output.model_output)
    output.zero_grad()
    metric.backward()
    return AttributionGrads(
        metric=metric,
        model_output=output.model_output,
        model_activations=output.model_activations,
        sae_activations=output.sae_activations,
    )


def calculate_feature_attribution(
    model: HookedSAETransformer,
    input: Any,
    metric_fn: Callable[[torch.Tensor], torch.Tensor],
    track_hook_points: list[str] | None = None,
    include_saes: dict[str, SAE] | None = None,
    return_logits: bool = True,
    include_error_term: bool = True,
) -> Attribution:
    """
    Calculate feature attribution for SAE features and model neurons following
    the procedure in https://transformer-circuits.pub/2024/march-update/index.html#feature-heads.
    This include the SAE error term by default, so inserting the SAE into the calculation is
    guaranteed to not affect the model output. This can be disabled by setting `include_error_term=False`.

    Args:
        model: The model to calculate feature attribution for.
        input: The input to the model.
        metric_fn: A function that takes the model output and returns a scalar metric.
        track_hook_points: A list of model hook points to track activations for, if desired
        include_saes: A dictionary of SAEs to include in the calculation. The key is the hook point to apply the SAE to.
        return_logits: Whether to return the model logits or loss. This is passed to TLens, so should match whatever the metric_fn expects (probably logits)
        include_error_term: Whether to include the SAE error term in the calculation. This is recommended, as it ensures that the SAE will not affecting the model output.
    """
    # first, calculate gradients wrt to the metric_fn.
    # these will be multiplied with the activation values to get the attributions
    outputs_with_grads = calculate_attribution_grads(
        model,
        input,
        metric_fn,
        track_hook_points,
        include_saes=include_saes,
        return_logits=return_logits,
        include_error_term=include_error_term,
    )
    model_attributions = {}
    model_activations = {}
    model_grads = {}
    sae_feature_attributions = {}
    sae_feature_activations = {}
    sae_feature_grads = {}
    sae_error_proportions = {}
    # this code is long, but all it's doing is multiplying the grads by the activations
    # and recording grads, acts, and attributions in dictionaries to return to the user
    with torch.no_grad():
        for name, act in outputs_with_grads.model_activations.items():
            assert act.grad is not None
            raw_activation = act.detach().clone()
            model_attributions[name] = (act.grad * raw_activation).detach().clone()
            model_activations[name] = raw_activation
            model_grads[name] = act.grad.detach().clone()
        for name, act in outputs_with_grads.sae_activations.items():
            assert act.feature_acts.grad is not None
            assert act.sae_out.grad is not None
            raw_activation = act.feature_acts.detach().clone()
            sae_feature_attributions[name] = (
                (act.feature_acts.grad * raw_activation).detach().clone()
            )
            sae_feature_activations[name] = raw_activation
            sae_feature_grads[name] = act.feature_acts.grad.detach().clone()
            if include_error_term:
                assert act.sae_error.grad is not None
                error_grad_norm = act.sae_error.grad.norm().item()
            else:
                error_grad_norm = 0
            sae_out_norm = act.sae_out.grad.norm().item()
            sae_error_proportions[name] = error_grad_norm / (
                sae_out_norm + error_grad_norm + EPS
            )
        return Attribution(
            model_attributions=model_attributions,
            model_activations=model_activations,
            model_grads=model_grads,
            sae_feature_attributions=sae_feature_attributions,
            sae_feature_activations=sae_feature_activations,
            sae_feature_grads=sae_feature_grads,
            sae_errors_attribution_proportion=sae_error_proportions,
        )


# prompt = " Tiger Woods plays the sport of"
# pos_token = model.tokenizer.encode(" golf")[0]
prompt = "In the beginning, God created the heavens and the"
pos_token = model.tokenizer.encode(" earth")
neg_token = model.tokenizer.encode(" sky")


def metric_fn(
    logits: torch.tensor,
    pos_token: torch.tensor = pos_token,
    neg_token: torch.Tensor = neg_token,
) -> torch.Tensor:
    return logits[0, -1, pos_token] - logits[0, -1, neg_token]


feature_attribution_df = calculate_feature_attribution(
    input=prompt,
    model=model,
    metric_fn=metric_fn,
    include_saes={sae.cfg.hook_name: sae},
    include_error_term=True,
    return_logits=True,
)

In [ ]:
from transformer_lens.utils import test_prompt

test_prompt(prompt, model.to_string(pos_token), model)

In [ ]:
tokens = model.to_str_tokens(prompt)
unique_tokens = [f"{i}/{t}" for i, t in enumerate(tokens)]

px.bar(
    x=unique_tokens,
    y=feature_attribution_df.sae_feature_attributions[sae.cfg.hook_name][0]
    .sum(-1)
    .detach()
    .cpu()
    .numpy(),
)

In [ ]:
def convert_sparse_feature_to_long_df(sparse_tensor: torch.Tensor) -> pd.DataFrame:
    """
    Convert a sparse tensor to a long format pandas DataFrame.
    """
    df = pd.DataFrame(sparse_tensor.detach().cpu().numpy())
    df_long = df.melt(ignore_index=False, var_name="column", value_name="value")
    df_long.columns = ["feature", "attribution"]
    df_long_nonzero = df_long[df_long["attribution"] != 0]
    df_long_nonzero = df_long_nonzero.reset_index().rename(
        columns={"index": "position"}
    )
    return df_long_nonzero


df_long_nonzero = convert_sparse_feature_to_long_df(
    feature_attribution_df.sae_feature_attributions[sae.cfg.hook_name][0]
)
df_long_nonzero.sort_values("attribution", ascending=False)

In [ ]:
for i, v in (
    df_long_nonzero.query("position==8")
    .groupby("feature")
    .attribution.sum()
    .sort_values(ascending=False)
    .head(5)
    .items()
):
    print(f"Feature {i} had a total attribution of {v:.2f}")
    html = get_dashboard_html(
        sae_release="gpt2-small",
        sae_id=f"{sae.cfg.hook_layer}-res-jb",
        feature_idx=int(i),
    )
    display(IFrame(html, width=1200, height=300))

In [ ]:
for i, v in (
    df_long_nonzero.groupby("feature")
    .attribution.sum()
    .sort_values(ascending=False)
    .head(5)
    .items()
):
    print(f"Feature {i} had a total attribution of {v:.2f}")
    html = get_dashboard_html(
        sae_release="gpt2-small",
        sae_id=f"{sae.cfg.hook_layer}-res-jb",
        feature_idx=int(i),
    )
    display(IFrame(html, width=1200, height=300))

# Advanced: Making U-Maps